### ISSUE TITLE
Dashboard filters don't have the same layout than others filters

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5209] opened 2024-09-30 06:37 UTC
Dashboard : 
![image](https://github.com/user-attachments/assets/5ca98927-70aa-4828-8c89-b411ab8117f1)
![image](https://github.com/user-attachments/assets/c0138411-4146-4494-8b07-411c877dd113)

Flows filters: 
![image](https://github.com/user-attachments/assets/9806eb2d-ac4c-4316-88ce-cac011e73e74)

Logs filters: 
![image](https://github.com/user-attachments/assets/33dca683-ad61-4be6-9cc6-9a9ebf90e75c)

- Use the standard 1px border 
- Keep the bottom margin on responsive layouyt
- There is no collapse button on small resolution on dashboard 
- the Absolute / Relative picker on logs is not vertical align 
- on small resolution, the absolute / relative filters is going outside of the screen

**Comment by jayg2309** [comment] 2024-10-06 17:17
@tchiotludo @MilosPaunovic  I would like to work on this issue

**Comment by MilosPaunovic** [comment] 2024-10-06 17:26
@jayg2309 Go for it! :rocket:

**Comment by MilosPaunovic** [comment] 2024-10-16 09:40
@jayg2309  any progress on this?

**Comment by jayg2309** [comment] 2024-10-17 01:18
Hey @MilosPaunovic 
I'm currently unable to work on the issue assigned to me due to some challenges on my end.  I sincerely apologize for any inconvenience this may cause. 
Please feel free to unassign me so someone else can take over.

**Comment by JoeCelaster** [comment] 2024-10-20 12:40
Can i work on this Project ? @MilosPaunovic

**Comment by anna-geller** [comment] 2024-11-08 13:01
closing as the issue is tackled here https://github.com/kestra-io/kestra/issues/4664#issuecomment-2462552277 (part already merged)

**Closed as completed by anna-geller** 2024-11-08 13:01 UTC
Labels: area/frontend, good first issue
