### ISSUE TITLE
Export, Delete, Disable flows doesn't format `code` tag correctly 

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#6113] opened 2024-11-26 13:00 UTC
### Describe the issue

I selected 2 flows under the Flows tab and press Export. The confirmation message still says `<code>` rather than formatting it correctly.

![Screenshot 2024-11-26 at 13 01 00](https://github.com/user-attachments/assets/81757362-b829-4415-94eb-7b1bdbe832e6)

![Screenshot 2024-11-26 at 13 00 01](https://github.com/user-attachments/assets/091ca143-1333-4951-a298-6ac2f379678f)

### Environment

- Kestra Version: develop OSS

**Comment by MilosPaunovic** [comment] 2024-11-26 13:55
Adding a note that this happens for deleting and disabling flow confirm dialogs.

Also, take to be taken into account when providing solution https://github.com/kestra-io/kestra/pull/5933/files.

**Comment by anna-geller** [comment] 2024-11-29 19:17
seems like a duplicate of an issue that already has a PR :) https://github.com/kestra-io/kestra/issues/5981

**Closed as not planned by anna-geller** 2024-11-29 19:17 UTC
Labels: area/frontend
