### ISSUE TITLE
Query parameters lost when navigating on search views

### ISSUE THREAD

**Issue by yvrng** [kestra-io/kestra#3387] opened 2024-03-25 15:27 UTC
### Describe the issue

When I navigate to https://kestra/ui/flows or https://kestra/ui/executions with pre-filled query parameters such as `?namespace=dev&state=SUCCESS&q=my+query`, they are ignored and deleted once the page is loaded.

This also happens when you simply refresh the page with the F5 key.

`page` and `size` do not seem to be concerned.

I don't reproduce it in 0.14.4, so perhaps a small regression introduced in version 0.15.

### Environment

- Kestra Version: 0.15.8
- Operating System (OS/Docker/Kubernetes): Kubernetes (Kafka / ES / GCS)

**Comment by anna-geller** [comment] 2024-03-25 21:27
interesting that it should have been fixed in 0.15.8 https://github.com/kestra-io/kestra/issues/2890

thanks for reporting it!

**Comment by brian-mulier-p** [comment] 2024-05-23 09:29
to backport to 0.16

**Comment by brian-mulier-p** [comment] 2024-05-23 09:31
Seems to be related to per-tenant filter cache management as I only reproduce on EE

**Closed** 2024-05-23 16:47 UTC
Labels: bug, frontend, customer-request

**Comment by brian-mulier-p** [comment] 2024-05-23 17:47
Fixed in v0.16.8 :+1:
