### ISSUE TITLE
Allow Restarting Executions in a QUEUED, CREATED or RUNNING state 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4260] opened 2024-07-07 21:02 UTC
related https://github.com/kestra-io/kestra/issues/4840 
Currently, you can only restart Executions in a terminal state (Failed, Killed, Warning). To deal with executions that are stuck in a transient state, user currently needs to:
- Kill those stuck Executions
- Wait until those executions are Killed
- Then, restart them.

This is tedious. We want to hide this complexity so that user can just hit the "Restart" button and kestra should handle killing and restarting those executions automatically.

![image](https://github.com/kestra-io/kestra/assets/86264395/d43fc92e-7901-447e-b65b-381e6059027b)

Restarting such Executions should naturally generate an audit log entry for troubleshooting.

**Comment by johnkm516** [comment] 2024-07-12 00:54
I'd like to reference an issue I created on exactly this : kestra-io/kestra-ee#1726

Personally I think there should be a base timeout on the executor which automatically fails the task if the task cannot be created. Unless there is someone monitoring the executions and spot the flows stuck in the CREATED state, there is no way for administrators to know that the flows are indeed stuck or not. The alerting I have set up would not detect this.

**Comment by anna-geller** [comment] 2024-07-12 06:19
We were wondering about this kind of timeout, but the backend team mentioned this would not be feasible within the Execution itself (cc @loicmathieu). However, long-term you're totally right that you should be able to add some form of SLA for Executions e.g.:
- if more than 10 Executions are stuck in a CREATED state for longer than 30 minutes, send an alert and kill those stuck executions
- or: if any execution is stuck in a CREATED state for longer than 5 minutes, send an alert to DevOps with a link to the Execution.

Some of my thinking and possible solutions we can consider https://github.com/kestra-io/kestra/issues/3350

**Comment by loicmathieu** [comment] 2024-10-14 08:40
I wonder if this issue is not the same as this one: https://github.com/kestra-io/kestra-ee/issues/406

To restart executions blocked in QUEUED/CREATED/RUNNING we should resubmit the execution to the queue.

**Comment by johnkm516** [comment] 2024-10-24 00:57
@loicmathieu 
I can't see what the issue is on kestra-ee as I do not have access to it, but I think this feature is really needed. 
There's quite a few instances of executor and scheduler crashes, I've reported many already as support tickets with two more today. The crashes are fine as long as it doesn't affect executions, but the problem is that it does in fact affect executions. As per my screenshot below, when the executor crashes while in the midst of creating a task, when the executor comes back up the flows / tasks are stuck in the CREATED state forever : 

![image](https://github.com/user-attachments/assets/ab67f8e7-6e23-4dc9-88a8-678f76318544)

All of these flows run for 5 minutes max. Yet they have been stuck like this for the past day ~ week, and will stay that way until I kill the executions manually. Will the feature mentioned in the kestra-ee issue fix this?

**Comment by anna-geller** [comment] 2024-10-24 08:26
Hi John, the issue here is to make it easier to restart such stuck executions. Currently, you'd need to first Kill those stuck Executions, wait until those executions are Killed and only when they moved to the terminal state (Killed), you can manually restart them -- too many steps for the end user, this issue is to allow that in one click and let Kestra handle the killing, waiting for termination and restarting.

**Comment by johnkm516** [comment] 2024-10-28 01:36
@anna-geller 
Hi Anna, would it be possible to explore a more automated solution? Tasks stuck in the CREATED state for an extended amount of time are obviously stuck. I do not want to kill the entire flow execution and restart the flow, as in such cases there might be previous tasks that were successful that might run twice when it shouldn't. 

There should be some sort of reassigning of workers and a renewal of the task execution if a task is stuck in the CREATED state for a set amount of time that the administrator sets.

**Comment by anna-geller** [comment] 2024-10-28 09:28
Hi John, that's also on the roadmap to allow automated action if some workflows don't match given SLA conditions incl. this use case of stuck executions https://github.com/kestra-io/kestra/issues/3350 

Ideally, we should never have executions stuck in a CREATED state, and as a first step, let's try to find the root cause. Last time we talked about it, you mentioned the issue of stuck task runs because they were using a wrong worker group key, so we added build-time validation + dedicated UI page for troubleshooting https://kestra.io/blogs/release-0-19#worker-groups-ui-page-and-validation 

To help you on this further, I opened an issue internally to further improve `workerGroup` -- some possibilities (just ideas, I don't know yet how this will be handled technically):

```yaml
    workerGroup:
      key: yourKey
      fallback: REASSIGN # or QUEUE, CANCEL, FAIL
```

**Comment by loicmathieu** [comment] 2024-11-05 12:17
Queued executions could now be unqueued thanks to https://github.com/kestra-io/kestra/pull/5776

**Comment by anna-geller** [comment] 2024-11-07 09:08
What are the next steps here? Ideally, when a user clicks on the Restart button in the Bulk Actions with multiple executions in non-terminal states selected, instead of raising an error `Illegal state: Execution must be terminated to be restarted, the current state is CRETED/QUEUED/RUNNING`, we should:
1. Unqueue those in the `QUEUED` state so that they move to `RUNNING`
2. Kill + then restart those in `CREATED`/`RUNNING` states (or resubmit them to the queue?)

Is it feasible, @loicmathieu?

To make it safer, we can display a message "Are you sure you want to restart those non-terminated executions? Kestra will attempt to restart those executions while ignoring any concurrency limits if they are set." - grey Cancel + purple Restart buttons

**Comment by loicmathieu** [comment] 2024-11-07 10:06
> Unqueue those in the QUEUED state so that they move to RUNNING

We can do this but it's different to restart which creates a new execution, here the same execution will be forced running.

> Kill + then restart those in CREATED/RUNNING states (or resubmit them to the queue?)

We can't do that as killing is async. Or maybe we can but the result may not be guaranteed: the previous execution may still ends as killing is not guaranteed, and the new execution may not work if there is an underlying issue.

I'm not comfortable with multiple actions on a unique button. Most of the time if you need that, it means there was a bug in the executor (or you did something wrong like deleting running executions). And doing multiple actions like that has implications that, if we didn't explain to the user, may be surprising.

Maybe we need a "new button" (I know we have plenty of them) to "force process" an execution:
- if CREATED -> move to RUNNING (this can lead to concurrency limit exceeded or duplicate task execution)
- if RUNNING -> resubmit it as RUNNING (this can lead to duplicate task execution)
- if QUEUED -> UNQUEUE (like if you click on the existing enqueue button)
- if PAUSED -> RESUME (like if you click on the existing resume button)
- if one of the terminated state: we can either error or ignore (via a flag or everytime)
Like a global "continue switch" with a big WARNING on the implications and no guarantee of the correct processing.
We may need to restict this button to administrators ...

**Comment by anna-geller** [comment] 2024-11-07 13:21
this is great! don't worry about too many bulk actions, I can check with Nico how to make them easier to display

1. Naming: "Force Run" or "Force Resume"? "Process" can be ambiguous e.g. we do process orchestration...
2. "Ignore Terminated" toggled on (or checked) by default?

**Comment by loicmathieu** [comment] 2024-11-07 14:43
I'm OK with "Force Run", not "Force Resume" as resume implies pause.

**Comment by loicmathieu** [comment] 2024-11-08 14:59
- We can now "unqueu" an execution
- We can now "force run" an execution (but it's always a bad idea)
- We can now configure what to do when no workers are available to run a task on a worker group

This should be enough, I'm closing this one.

**Closed as completed by loicmathieu** 2024-11-08 14:59 UTC
Labels: area/backend
