### ISSUE TITLE
Users cannot see custom blueprints

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4630] opened 2024-08-12 01:00 UTC
### Describe the issue

All non-superadmin users cannot see custom blueprints. 
This includes users with Admin roles in all namespaces. 
Note : My environment uses tenants.

### Environment

- Kestra Version: 0.19-SNAPSHOT
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by anna-geller** [comment] 2024-08-12 07:39
Hi John, I couldn't reproduce -- could you cross-check in a different browser or by recreating the role and reassigning to the user? Some permissions are cached, so worth trying in an incognito browser mode to be sure

![image](https://github.com/user-attachments/assets/76f7fcb9-b94e-453c-9966-27e8d98b605f)

![image](https://github.com/user-attachments/assets/56f65d41-341b-4ce7-befc-5c8caf185ce6)

**Comment by anna-geller** [comment] 2024-08-12 07:47
Given you're on develop, perhaps try re-pulling the Docker image? It could be we use a different version in the end based on which state of develop you're currently on 👍 this could explain why we can't reproduce

**Comment by johnkm516** [comment] 2024-08-12 07:49
Hmmm... Here's what my roles look like : 

<img width="954" alt="image" src="https://github.com/user-attachments/assets/bb7927c0-cf78-4e98-b362-d9a3e26c18c7">

As you can see cjo1 has Admin role for all the namespaces but cannot see the Custom Blueprints : 

<img width="943" alt="image" src="https://github.com/user-attachments/assets/32511e03-af88-44c3-af97-2ad62401e04c">

I'll try repulling with latest develop image and see if that works.

**Comment by anna-geller** [comment] 2024-08-12 07:55
yeah, another aspect is that those predefined roles might not automatically have all roles; they are added once you create a tenant but not updated after that. They are created mostly for convenience so that users new to kestra don't need to click through all the permissions and actions (Cread, Read, Update, Delete) manually. It's always best to create custom roles so that you have full control over what permissions are in them.

**Comment by johnkm516** [comment] 2024-08-12 08:11
> yeah, another aspect is that those predefined roles might not automatically have all roles; they are added once you create a tenant but not updated after that. They are created mostly for convenience so that users new to kestra don't need to click through all the permissions and actions (Cread, Read, Update, Delete) manually. It's always best to create custom roles so that you have full control over what permissions are in them.

I pulled the latest develop image, and created another custom Role called "AllPermissions" which gave all possible permissions, and then gave this role for all namespace to the account cjo1 : 

<img width="953" alt="image" src="https://github.com/user-attachments/assets/d4e35147-99b9-4fee-81ce-a6ae59bbc0cb">

and I still cannot see custom blueprints tab. I'm on Chrome, in incognito mode. I wonder why you cannot reproduce? I thought the problem was tenants but apparently not...

**Comment by anna-geller** [comment] 2024-08-12 08:36
the magic of frontend that hasn't been fully QAed yet on `develop` :) let's switch to the `latest` production image for now, close the issue and we can reopen the issue if it appears on `latest`, sounds good?

**Comment by johnkm516** [comment] 2024-08-13 01:37
I've tried creating a new account, and giving the new account Superadmin access. I still cannot see Custom Blueprints : 

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5646334c-bcdf-48ca-af01-8e35763dfa6a">

<img width="942" alt="image" src="https://github.com/user-attachments/assets/ee735425-bef9-464f-8271-41d65d54b938">

I'm hoping to meet with @paulgrainger85 today to try to find out what the cause is.

**Comment by paulgrainger85** [comment] 2024-08-13 15:32
I've been able to reproduce it here, I will give the feedback to the team

**Comment by MilosPaunovic** [comment] 2024-09-09 10:29
@Ben8t could you check this one, as well? 🍀

**Comment by Ben8t** [comment] 2024-09-09 12:00
@MilosPaunovic - on 0.19.0:develop with super admin I'm able to create a blueprints, but can't see them with error `Internal Server Error: Internal server error: Client ‘strapi’: Internal Server Error`


https://github.com/user-attachments/assets/914d004a-1ddd-44e4-95ea-b652a1459d14

**Comment by MilosPaunovic** [comment] 2024-09-10 07:56
Changes are pushed, this is now ready for final test @Ben8t.

**Comment by Ben8t** [comment] 2024-09-13 08:07
LGTM 🚀

**Closed as completed by Ben8t** 2024-09-13 08:07 UTC
Labels: kind/customer-request
