### ISSUE TITLE
SQL query in queue that could lead to a bug 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5426] opened 2024-10-11 16:32 UTC
![image](https://github.com/user-attachments/assets/76820ca7-7506-4218-b202-674ed073ca34)

https://github.com/kestra-io/kestra/blob/e12ba7d6064328aa4e6b109420871dc688594706/jdbc/src/main/java/io/kestra/jdbc/runner/JdbcQueue.java#L182-L193

I didn't see the point to fetch the `maxOffset` for all queues (missing the where `type = ?` or the `consumer_group = ?`) and I think it could lead to a bug. The query is also not using any index and will be costly.

**Comment by Aryant-Tripathi** [comment] 2024-10-12 18:08
@tchiotludo may I allow to work on this issue? Also, didn't get requirement what we need to do here, may you explain little bit what we need to do here actually?

Sorry for all this, as I am very new to kestra, but really want to contribute and learn around here.

**Comment by loicmathieu** [comment] 2024-10-14 07:14
@tchiotludo `offset` is a PK so there is an index, but I agree it's stange. I need to dig a little as I think it is like that since the beginning.

@Aryant-Tripathi this is an internal are of Kestra not easy for people not knowing how Kestra works in details, I strongly suggest you take a look at [good first issues ](https://github.com/kestra-io/kestra/issues?q=is%3Aopen+label%3Akind%2Fquick-win+label%3A%22good+first+issue%22)instead.

**Comment by loicmathieu** [comment] 2024-11-07 08:58
@tchiotludo this methods is used in tests to listen to the queue (mainly for execution or logs) and being able to receive messages to assert them. They do use the index on the `offset` column.
They are used only by the TestsUtils and the RunnerUtils when creating execution and awaiting for the execution to be processed.

I think they are safe.
If you agree, can we close this issue?

**Comment by tchiotludo** [comment] 2024-11-07 09:15
No it's used inside the main application since it was reported by google query performance. 
We need to find where, because it seems to consume a lot of resources.

**Comment by loicmathieu** [comment] 2024-11-07 10:21
I overlooked, it's used in an other method in the queue that is used in a bunch of places:
- FlowListeners
- Worker
- ExecutionController (to follow the execution)
- LogController (to follow the execution)

I think both usages inside controllers are legit. We cannot do any other way as we need to query the "latest exec/log" and filter on the one we want to display in the UI.

For the FlowListeners and the Worker, as I remember, it's also needed as we want to have all flows and all execution killed in those, so we cannot use the other method that load balances the poll between all consumers.

We the query to get the max offset, we can add the consumer group (but it's always null in all code path I analyse) and the queue_type, it may improve the performance if this query is the one that bring performance issue.

**Comment by loicmathieu** [comment] 2024-11-07 11:15
@tchiotludo the best I can do easily is to add the consumerGroup and queueType condition to the fetch of the max offset, see https://github.com/kestra-io/kestra/pull/5834/files#diff-70145e96cdd165341d305afa24a65711a2819dba6297a2a93cacb0853c4228d8R224

If it's OK for you, I'll close this issue when the PR is merged.

**Comment by loicmathieu** [comment] 2024-11-07 11:20
Another thing that comes to my mind is that from the ExecutionController and the LogController, when we follow executions/logs we will poll the DB with the configured poll frequency which is by default very low (25ms), as those are for humans following the exec/log, a lower frequency would still give a user perception of "real time", so if we're able to pass the poll frequency to this method we can for ex poll each 100ms instead.

This is a more involved change but would lower the database load if a lot of users are following logs or executions.

**Comment by tchiotludo** [comment] 2024-11-07 12:47
yes the main things that I don't understand is why we need it without `type`? you will received a lot of unneeded values no ?

**Comment by loicmathieu** [comment] 2024-11-07 12:52
It's only the main offset query that didn't contain the type, it then calls `receiveFetch` with that offset and it correctly have a condition on the type.

**Comment by tchiotludo** [comment] 2024-11-07 13:08
yes but this is the bug, the main offset fetch without a type don't make any sense IMO ? 
It's the goal of this ticket to search, but IMO it's a bug

**Comment by loicmathieu** [comment] 2024-11-07 14:42
> yes but this is the bug, the main offset fetch without a type don't make any sense IMO ?

It does make sense as basically what we want is to start polling from now and don't care of previous messages.
Anyway, I added filters on consumer_group and type if it can help to select a better index.
So this is not a bug, but it may not be optimal.

**Comment by loicmathieu** [comment] 2024-11-26 09:35
Fixed by https://github.com/kestra-io/kestra/pull/5834

**Closed as completed by loicmathieu** 2024-11-26 09:35 UTC
Labels: area/backend
