### ISSUE TITLE
[UI] Blueprint tags and title should be in the same line

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6059] opened 2024-11-22 16:33 UTC
### Describe the issue

![image](https://github.com/user-attachments/assets/bf38a83b-f981-47b3-8b36-3dbb3de365a2)

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment] 2024-11-22 21:05
Duplicate of https://github.com/kestra-io/kestra/issues/6033.

**Closed as not planned by MilosPaunovic** 2024-11-22 21:05 UTC
Labels: area/frontend, kind/quick-win, good first issue
