### ISSUE TITLE
namespace files overwritten with code of a different namespace file

### ISSUE THREAD

**Issue by gvanderweerd** [kestra-io/kestra#4730] opened 2024-08-23 11:23 UTC
### Describe the issue

In my company we use Kestra to develop datapipelines. We store files as namespace files and develop in the online editor.
I myself use Brave browser to edit code in the namespace files. Sometimes it happens that I am working on multiple python modules for example: 
I will have namespace_name/database/query.py & namespace_name/tasks/task_name.py open in my editor. Sometimes when I click on "Save" it overwrites the code of one of the files I have open with the code of the other file. We use git-push to backup namespace files on a daily basis. We can revert from there but sometimes lose a day of development work because of this issue.

### Environment

- Kestra Version: 0.17.2
- Operating System (OS/Docker/Kubernetes): Ubuntu 22.04.3 LTS / Docker: version 24.0.6

**Comment by anna-geller** [comment] 2024-08-25 21:45
thanks for the issue. This is a possible bug (since we need to map the tab with the right content)

**Comment by gvanderweerd** [comment] 2024-08-30 07:27
Thanks! Let me know if there is any progress. I spoke to our developers and some of them also encountered the same issue in Google Chrome browser.

**Comment by anna-geller** [comment] 2024-09-26 22:40
hey, I can't reproduce the issue on develop - see the video demo: https://share.descript.com/view/w3mG1X4Z1TX 

so if you saw it on 0.17.2, it's likely it will be fixed after upgrading to 0.19 that will be released next week

**Closed as completed by anna-geller** 2024-09-26 22:40 UTC
Labels: area/frontend
