### ISSUE TITLE
sub flow use wait: true will create many executions 

### ISSUE THREAD

**Issue by qianshengzj** [kestra-io/kestra#625] opened 2022-06-23 05:16 UTC
### Expected Behavior

trigger sub flow once and wait util the sub flow finish

### Actual Behaviour

![image](https://user-images.githubusercontent.com/21097532/175220321-e1c7017b-256c-4725-b6cd-1b51106ab082.png)
![image](https://user-images.githubusercontent.com/21097532/175220420-a61a5053-ccfa-440c-a5e5-261b4217265e.png)

### Environment Information

- Kestra Version: 0.4.7
- Operating System (OS / Docker / Kubernetes): docker
- Java Version (If not docker): openjdk11

**Comment by tchiotludo** [comment] 2022-06-23 05:48
Hey @qianshengzj, 

Strange, we have a lot of environment where that works

- Are you using the architecture with Kafka and elastic search with docker compose ?
- Does the bug happen all the time ?

With this informations, I'll try to reproduce

**Comment by qianshengzj** [comment] 2022-06-23 07:12
@tchiotludo 
this is my kafka docker-compose.yaml
`version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://{MY_IP}:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local`

    Container          Repository        Tag       Image Id      Size
----------------------------------------------------------------------
kafka_kafka_1       bitnami/kafka       latest   b7add9628c8e   626 MB
kafka_zookeeper_1   bitnami/zookeeper   latest   15e78766ee47   446 MB

this is some logs of kestra executor

![image](https://user-images.githubusercontent.com/21097532/175237252-9ad65e7c-d17b-4b01-95f8-fb0248ec11a0.png)

please give me some direction

**Comment by qianshengzj** [comment] 2022-06-23 09:41
its same as #240

**Comment by tchiotludo** [comment] 2022-06-23 09:42
I've try to reproduce the issue with no luck, can you share me the full flow as yaml please ?

**Comment by qianshengzj** [comment] 2022-06-23 11:56
`
id: sub_flow_test
namespace: io.kestra.tests
revision: 10
tasks:
  - id: sequential
    type: io.kestra.core.tasks.flows.Parallel
    tasks:
      - id: 1st
        type: io.kestra.core.tasks.flows.Flow
        namespace: io.kestra.tests
        flowId: template-test
        transmitFailed: true
        wait: true
      - id: "2st"
        type: io.kestra.core.tasks.flows.Flow
        namespace: io.kestra.tests
        flowId: template-test2
        transmitFailed: true
        wait: true
  - id: last
    type: io.kestra.core.tasks.debugs.Return
    format: "{{task.id}} > {{taskrun.startDate}}"
`
`
id: with-template
namespace: io.kestra.tests
tasks:
  - id: template
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - sleep 30
      - echo "{{ parent.outputs.args.aaaforward }}"
`
`
id: template-test
namespace: io.kestra.tests
revision: 4
tasks:
  - id: 2-template
    type: io.kestra.core.tasks.flows.Template
    namespace: io.kestra.tests
    args:
      aaaforward: asdsadsad1211
    templateId: with-template
`
`
id: template-test2
namespace: io.kestra.tests
revision: 1
tasks:
  - id: 2-template
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - exit 1

`

**Comment by tchiotludo** [comment] 2022-06-23 12:34
Hummm interesting, you are using template, it might be related, I'll look at these this night

**Comment by qianshengzj** [comment] 2022-06-24 02:40
sorry, I missing some task config for you

here is new config, i have test in my local docker environment

-------main task--------
id: sub_flow_test
namespace: io.kestra.tests
revision: 10
tasks:
  - id: parallel
    type: io.kestra.core.tasks.flows.Parallel
    tasks:
      - id: a-task
        type: io.kestra.core.tasks.flows.Flow
        namespace: io.kestra.tests
        flowId: sub2
        transmitFailed: true
        wait: true
      - id: b-task
        type: io.kestra.core.tasks.flows.Flow
        namespace: io.kestra.tests
        flowId: sub1
        transmitFailed: true
        wait: true
------------------------
id: sub1
namespace: io.kestra.tests
revision: 1
tasks:
  - id: template
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - sleep 30
      - echo "123123"
------------------------
id: sub2
namespace: io.kestra.tests
revision: 1
tasks:
  - id: template
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - exit 1
------------------------


![image](https://user-images.githubusercontent.com/21097532/175451344-dd67a87d-738c-430c-aaca-b3fc107b08e9.png)

**Comment by qianshengzj** [comment] 2022-06-24 08:15
i think the config "transmitFailed" will trigger this bug。

**Comment by tchiotludo** [comment] 2022-06-24 08:25
- If you keep the `wait:true` and remove `transmitFailed` you don't have the issue? 
- Do you have a 100% reproduction ?

**Comment by tchiotludo** [comment] 2022-06-24 19:11
OK got a reproduction! using `image: docker.io/bitnami/kafka:latest` that I can reproduce with `image: confluentinc/cp-kafka`, let's dig into that

**Comment by tchiotludo** [comment] 2022-06-24 20:40
Got it :tada: 
I can't reproduced because it was fixed with https://github.com/kestra-io/kestra/commit/4a61af45d668feab19313b9033826fa7075bf02b
Before this commit the issue can be be reproduced, not after

Please try with `dev` image and reopen if it don't work

**Closed by tchiotludo** 2022-06-24 20:40 UTC
Labels: bug
