### ISSUE TITLE
Chart tooltip does not disappear

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1311] opened 2023-05-16 09:07 UTC
### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/37600690/a78b46cb-3602-4e53-a8ff-0f601abbaba6)

### Environment Information

- Kestra Version: 0.8.1

**Comment by tchiotludo** [comment] 2023-05-16 09:35
duplicate of these one : https://github.com/kestra-io/kestra/issues/1302

**Closed by tchiotludo** 2023-05-16 09:35 UTC
Labels: bug
