### ISSUE TITLE
Improve Inputs naming

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5045] opened 2024-09-24 10:21 UTC
### Feature description

In the screenshot the inputs "Name" actually returns the Inputs "ID" so would be great to change the naming to "ID" rather what we have now "Name" 

![image](https://github.com/user-attachments/assets/05ebebde-e536-4c72-8a5a-e4901bc8454a)

**Comment by anna-geller** [comment] 2024-09-24 10:27
duplicate of https://github.com/kestra-io/kestra/issues/5047

**Closed as not planned by anna-geller** 2024-09-24 10:27 UTC
