### ISSUE TITLE
Add possibility to set an infinite number of retries (-1) and move the retry logic to the Executor

### ISSUE THREAD

**Issue by dantimofte** [kestra-io/kestra#2734] opened 2023-12-18 07:51 UTC
### Feature description

Hello, 

I have created a task with retry policy which automatically set it to 3 attempts. I’d like it to have an infinite number of retries so 

I looked in the code and found that it is using failsafe.RetryPolicy; which accepts maxAttempt = -1 for an unlimited number of retries however the web interface of Kestra does not allow integer values bellow `1`.

Is it possible to have this option?

Thank you

**Comment by anna-geller** [comment] 2023-12-19 13:59
Discussed it internally: it's possible but we need to make the retry logic at the executor level (and no more at the worker level)

**Comment by Skraye** [comment] 2023-12-26 15:26
@anna-geller looks like a lot a `do while` for me!

**Comment by anna-geller** [comment] 2023-12-29 16:40
@Skraye yup the outcome might be similar while staying more declarative (a while loop in YAML is not something we'd prioritize for now)

This one is definitely a nice and simple addition

**Comment by anna-geller** [comment] 2024-03-25 23:50
@Skraye, adding this to 0.16 only in case this is something that would be easy to tackle in bulk with all other retries enhancements you are working on; if complex, feel free to move to 0.17

**Comment by anna-geller** [comment] 2024-03-25 23:52
@dantimofte we are working on adding a While Loop task that seem very similar to what you're trying to accomplish - can you confirm whether while loop will solve the issue for you https://github.com/kestra-io/kestra/issues/3024? if so, we could close this issue

**Comment by tchiotludo** [comment] 2024-04-04 06:56
After investigation, we will not support infinite retries because it's really dangerous for Kestra. In Kestra, each attempts will be append on Execution, and large execution could lead to large performance issues (ui, executor, ...). 
Each Circuit breakers implementation have a default value for max retry to avoid this unexpected behavior. 
You could setup to a very large amount to emulate almost unlimited retry at your own risk.

**Closed by tchiotludo** 2024-04-04 06:56 UTC
Labels: enhancement

**Comment by dantimofte** [comment] 2024-04-04 07:25
Makes sense to me, thanks for considering it.
