### ISSUE TITLE
Source Search strangely claims 'no logs emitted' at first

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#5050] opened 2024-09-24 10:47 UTC
### Describe the issue

Doing a _Source Search_ from the _Flows_ the page will at first greet the user with : _No logs emitted so far_ . Which seems strange and a bit confusing.

![nologs](https://github.com/user-attachments/assets/9e36bb53-9354-4a27-a450-ccf545184069)

### Environment

- Kestra Version: 0.19.0-SNAPSHOT (d329c68)
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by smunteankestra** [comment] 2024-09-25 08:40
duplicate of https://github.com/kestra-io/kestra/issues/4841

**Closed as completed by smunteankestra** 2024-09-25 08:40 UTC
Labels: area/frontend
