### ISSUE TITLE
containerImage don't have any impact without providing taskRunner

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4200] opened 2024-07-01 21:20 UTC
When `taskRunner` is configured by `pluginDefaults`: 
```yaml
      tasks:
        defaults:
        - type: io.kestra.plugin.scripts.
          forced: true
          values:
            runner: "DOCKER"
```

using this flow: 
```yaml
    - id: python
      type: io.kestra.plugin.scripts.python.Script
      allowFailure: true
      containerImage: python:latest
      beforeCommands:
        - "pip install requests"
      script: | 
        import requests
        import socket
        print(socket.gethostname())

        response = requests.get('https://api.github.com/')
        print(response)
```

changing the `containerImage` has no effect, and the default image will be taken all the time 

Adding the `taskRunner` will make the `containerImage` works
```yaml
    - id: python
      type: io.kestra.plugin.scripts.python.Script
      containerImage: python:latest
      taskRunner: 
        type: io.kestra.plugin.scripts.runner.docker.Docker
```

**Comment by loicmathieu** [comment] 2024-07-09 07:14
This is by design, you either use the new taskRunner property that works with the containerImage property, or use the old runner property that works with the docker property.

You cannot mix both and I'm not sure it's a good idea to allow that as now there is a clear dichotomy: you either use one or the other facility.

**Comment by anna-geller** [comment] 2024-07-22 09:53
1. When using containerImage without specifying taskRunner or runner, it uses the default Docker-type taskRunner 
![image](https://github.com/user-attachments/assets/4584a320-9e85-4ccc-9b32-dd7912b6dbac)
2. When using runner, user would need to use docker.image to set the image rather than containerImage 

everything seems to work as expected

**Comment by tchiotludo** [comment] 2024-07-31 15:04
you should not have different behavior IMO, we should map old behavior to the new one. 

Meaning that: 
- `docker.image` will be set mapped inside the `containerImage`  
- `docker.image` & `containerImage` couldn't be set at the same time
- `docker.image` should be deprecated 
- `runner` should be deprecated 
- `runner` will be mapped to the corresponding task runners

**Comment by loicmathieu** [comment] 2024-08-08 15:27
This has been fixed in all plugins that uses our script facility and backported to 0.18.1.

**Closed as completed by loicmathieu** 2024-08-08 15:27 UTC
