### ISSUE TITLE
Unable to access ForEach 'next-to' task outputs

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#6498] opened 2024-12-17 14:50 UTC
### Describe the issue

I'm unable to access the current value of the **get_keys** task in each exec of the **for_each_keys** task.
I tried to find some hints in following guides :
- [loop](https://kestra.io/docs/how-to-guides/loop)
- [foreach](https://kestra.io/plugins/core/tasks/flow/io.kestra.plugin.core.flow.foreach)
- [taskruns](https://kestra.io/docs/workflow-components/tasks/taskruns)
And here's my reproducer :
```yaml
id: dump_namespace_kv
namespace: company.team

variables:
  kestra_base: "http://localhost:8080/kestra"
  basic_auth: "Basic ************"

tasks:
  - id: get_namespaces
    type: io.kestra.plugin.core.http.Request
    method: GET
    uri: "{{ vars.kestra_base }}/api/v1/namespaces/search"
    headers:
      Authorization: "{{ vars.basic_auth }}"

  - id: for_each_namespace
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ json(outputs.get_namespaces.body).results }}"
    concurrencyLimit: 0
    tasks:
      - id: get_keys
        type: io.kestra.plugin.core.http.Request
        method: GET
        uri: "{{ vars.kestra_base }}/api/v1/namespaces/{{ json(taskrun.value).id }}/kv/"
        headers:
          Authorization: "{{ vars.basic_auth }}"
      - id: for_each_key
        type: io.kestra.plugin.core.flow.ForEach
        concurrencyLimit: 0
        values: "{{ outputs.get_keys.body }}" # do not work, tried many other way but am unable to find the right one
        # no one really care about things after this line since its impossible to access the previous get_keys outputs
        tasks:
          - id: retrieve_values
            type: io.kestra.plugin.core.http.Request
            method: GET
            uri: "{{ vars.kestra_base }}/api/v1/namespaces/{{ json(parent.taskrun.value).id }}/kv/{{ json(taskrun.value).key }}"
            headers:
              Authorization: "{{ vars.basic_auth }}"
```

### Environment

- Kestra Version: 0.20.6 docker compose debian

**Comment by filip-paczynski** [comment] 2024-12-19 13:48
I had a similar problem recently. In my case it was (nested) `If` inside `ForEach` (on 0.19.x).

Anyway, I got around the problem by using `parents[0]`, `parents[1]` and so forth.  
You might want to experiment with different indexes.

Details:
https://kestra.io/docs/workflow-components/tasks/taskruns#parent-vs-parents-in-nested-flowable-tasks

**Comment by loicmathieu** [comment] 2024-12-20 10:23
As `get_keys` is inside a ForEach, there are multiple output for each task run.
To access the output you must use the special syntax `outputs.get_keys[taskrun.value].body` or with the special Pebble function `currentEachOutput('get_keys').body`.

Closing it now as it's not a bug.
But I'll forward this to our content writer team to enhance the documentation.

**Closed as completed by loicmathieu** 2024-12-20 10:23 UTC
Labels: area/backend
