### ISSUE TITLE
[UI] Gantt view not updated anymore after a Pause task

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5503] opened 2024-10-16 15:56 UTC
### Describe the issue

Using the following flow:

```yaml
id: sandbox
namespace: company.team

tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    delay: PT5S
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "Hello World"
```

After triggering the flow, the UI goes to the Gantt view.
After the pause task is executed, the Gantt is not updated with the new Log task, but refreshing the page shows the task.

See the screen share: 
[screen-capture (4).webm](https://github.com/user-attachments/assets/79c6a784-024f-492c-9f9f-e7142bef7a2b)

### Environment

- Kestra Version: 0.20.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by LidiaDomingos** [comment] 2024-10-16 17:49
Hi @loicmathieu!! I would like to work on it if possible!

**Comment by MilosPaunovic** [comment] 2024-10-17 06:13
Absolutely, go for it @LidiaDomingos! 🚀

**Comment by LidiaDomingos** [comment] 2024-10-19 03:55
Hi again @loicmathieu !! I tried to run locally with the backend running on docker but I keep getting an error "Failed to resolve import "Pre-transform error: Failed to resolve import "#build/mdc-image-component.mjs" from "node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue". Does the file exist?" and indeed I cant find that file. Any ideia what could be? My node is v18.20.4

**Comment by MilosPaunovic** [comment] 2024-10-19 07:27
That problem should've been amended, try to pull latest changes from `develop`, @brian-mulier-p could confirm.

**Comment by LidiaDomingos** [comment] 2024-10-19 16:07
I am already up to date! https://github.com/LidiaDomingos/kestra

**Comment by MilosPaunovic** [comment] 2024-10-20 18:05
@LidiaDomingos Try to check out answers on [this thread on Slack](https://kestra-io.slack.com/archives/C03G1PH4GBS/p1729036965683069), as the person had the same issue.

**Comment by MilosPaunovic** [comment] 2024-10-20 18:17
Okay, @LidiaDomingos, we have response on Slack, on [this](https://kestra-io.slack.com/archives/C03G1PH4GBS/p1729447504833689?thread_ts=1729036965.683069&cid=C03G1PH4GBS) tread.

> That was nuxtjs/mdc package that is giving the conflict downgrading it to 0.8.3 will solve the problem.

> Steps:
> Delete the package-lock.json file and node_modules folder.
> Pull the latest changes
> Do Npm i
> Open the package-lock.json file,change the @nuxtjs/mdc version to 0.8.3
> Again do Npm install, it will resolve your problem.

Let me know if this does it for you.

**Comment by LidiaDomingos** [comment] 2024-10-20 21:56
It worked!! thank you so much @MilosPaunovic

**Comment by MilosPaunovic** [comment] 2024-11-12 10:24
Is there any progress on this @LidiaDomingos?

**Comment by MilosPaunovic** [comment] 2024-11-14 08:19
This seems to be fixed now, after we've merged https://github.com/kestra-io/kestra/pull/5829. Could you double check to confirm @Ben8t?

**Comment by anna-geller** [comment] 2024-11-18 22:47
Milos yup, confirmed it's working now, thx a lot!

**Closed as completed by anna-geller** 2024-11-18 22:47 UTC
Labels: area/frontend
