### ISSUE TITLE
Error running python scripts on Oracle Cloud Infrastructure Ampere A1 environment

### ISSUE THREAD

**Issue by venturanc** [kestra-io/kestra#4410] opened 2024-07-23 22:37 UTC
### Describe the issue

Starting this issue based on a recommendation from the slack channel: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1720715245963489

Issue: I'm unable to run any flows that use python. Suspect it is due to the platform but even specifying an image that should be cross-platform such as python:slim does not work.

Here's the test flow (running the same test flow without specifying a different containerImage and using the default Kestra image also fails with the exact same error messages):
```
id: pipPackagesDocker
namespace: company.team

tasks:
  - id: run_python
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:slim
    beforeCommands:
      - pip install requests kestra > /dev/null
    warningOnStdErr: false
    script: | 
      import requests
      import json

      response = requests.get("https://api.github.com")
      data = response.json()
      print(data)
```
Running this produces these logs:
```
kestra-kestra-1    | 2024-07-23 22:16:50,529 INFO  main         o.f.core.internal.command.DbMigrate Current version of schema "public": 1.20
kestra-kestra-1    | 2024-07-23 22:16:50,541 INFO  main         o.f.core.internal.command.DbMigrate Schema "public" is up to date. No migration necessary.
kestra-kestra-1    | 2024-07-23 22:16:51,989 INFO  standalone   io.kestra.cli.AbstractCommand Starting Kestra with environments [cli]
kestra-kestra-1    | 2024-07-23 22:16:52,145 INFO  standalone   i.kestra.core.plugins.PluginScanner Registered 72 core plugins (scan done in 143ms)
kestra-kestra-1    | 2024-07-23 22:16:53,251 INFO  standalone   i.kestra.core.plugins.PluginScanner Registered 427 plugins from 82 groups (scan done in 1097ms)
kestra-kestra-1    | 2024-07-23 22:16:54,098 INFO  standalone   io.kestra.cli.AbstractCommand Server Running: http://36d4f39d3401:8080, Management server on port http://36d4f39d3401:8081/health
kestra-kestra-1    | 2024-07-23 22:16:56,480 INFO  standalone   i.k.w.services.FlowAutoLoaderService Loaded 0 "Getting Started" flows from community blueprints. You can disable this feature by setting 'kestra.tutorial-flows.enabled=false'.
kestra-kestra-1    | 2024-07-23 22:17:01,521 WARN  service-liveness-coordinator-task s.AbstractServiceLivenessCoordinator Detected non-responding service [id=9JGzkcPKSppbs9lYFNdFI, type=EXECUTOR, hostname=36d4f39d3401] after timeout (534470ms).
kestra-kestra-1    | 2024-07-23 22:17:01,522 WARN  service-liveness-coordinator-task s.AbstractServiceLivenessCoordinator Detected non-responding service [id=4jW3Zdwm3d1VCGmNSfiYm1, type=SCHEDULER, hostname=36d4f39d3401] after timeout (534466ms).
kestra-kestra-1    | 2024-07-23 22:17:01,522 WARN  service-liveness-coordinator-task s.AbstractServiceLivenessCoordinator Detected non-responding service [id=274330ad-de2e-4f58-916b-32a45b9ab2e7, type=WORKER, hostname=36d4f39d3401] after timeout (534468ms).
kestra-kestra-1    | 2024-07-23 22:17:01,522 WARN  service-liveness-coordinator-task s.AbstractServiceLivenessCoordinator Detected non-responding service [id=5wKNdCkEAqofMHxsN51ZBh, type=WEBSERVER, hostname=36d4f39d3401] after timeout (534477ms).
kestra-kestra-1    | 2024-07-23 22:18:37,216 INFO  default-nioEventLoopGroup-1-3 io.kestra.webserver.access 2024-07-23T22:18:36.875Z | GET /api/v1/executions/flows/company.team/pipPackagesDocker HTTP/1.1 | status: 200 | ip: 10.0.0.1 | length: 191 | duration: 331
kestra-kestra-1    | 2024-07-23 22:18:38,468 INFO  default-nioEventLoopGroup-1-4 io.kestra.webserver.access 2024-07-23T22:18:38.313Z | POST /api/v1/executions/company.team/pipPackagesDocker HTTP/1.1 | status: 200 | ip: 10.0.0.1 | length: 421 | duration: 154
kestra-kestra-1    | 2024-07-23 22:18:38,607 INFO  default-nioEventLoopGroup-1-5 io.kestra.webserver.access 2024-07-23T22:18:38.596Z | GET /api/v1/executions/flows/company.team/pipPackagesDocker HTTP/1.1 | status: 200 | ip: 10.0.0.1 | length: 191 | duration: 10
kestra-kestra-1    | 2024-07-23 22:18:38,864 INFO  jdbc-queue-Execution_0 flow.pipPackagesDocker [namespace: company.team] [flow: pipPackagesDocker] [execution: 5hTbdEIo65dDeBhx2UtMBD] Flow started
kestra-kestra-1    | 2024-07-23 22:18:39,880 INFO  worker_0     flow.pipPackagesDocker.run_python [namespace: company.team] [flow: pipPackagesDocker] [task: run_python] [execution: 5hTbdEIo65dDeBhx2UtMBD] [taskrun: 77RBbh2sWswtMYkwCQkF22] Type Script started
kestra-kestra-1    | 2024-07-23 22:18:39,921 INFO  WorkerThread f.p.5.77RBbh2sWswtMYkwCQkF22 Provided 0 input(s).
kestra-kestra-1    | 2024-07-23 22:18:39,946 INFO  WorkerThread f.p.5.77RBbh2sWswtMYkwCQkF22 Provided 1 input(s).
kestra-kestra-1    | 2024-07-23 22:18:41,188 WARN  docker-java-stream--822081929 f.p.5.77RBbh2sWswtMYkwCQkF22 exec /bin/sh: exec format error
kestra-kestra-1    | 2024-07-23 22:18:41,428 ERROR WorkerThread f.p.5.77RBbh2sWswtMYkwCQkF22 Command failed with code 1
kestra-kestra-1    | io.kestra.core.models.tasks.runners.TaskException: Command failed with code 1
kestra-kestra-1    |    at io.kestra.plugin.scripts.runner.docker.Docker.run(Docker.java:332)
kestra-kestra-1    |    at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:159)
kestra-kestra-1    |    at io.kestra.plugin.scripts.python.Script.run(Script.java:159)
kestra-kestra-1    |    at io.kestra.plugin.scripts.python.Script.run(Script.java:24)
kestra-kestra-1    |    at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:77)
kestra-kestra-1    |    at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:56)
kestra-kestra-1    | 2024-07-23 22:18:41,538 INFO  worker_0     flow.pipPackagesDocker.run_python [namespace: company.team] [flow: pipPackagesDocker] [task: run_python] [execution: 5hTbdEIo65dDeBhx2UtMBD] [taskrun: 77RBbh2sWswtMYkwCQkF22] Type Script with state FAILED completed in 00:00:02.675
kestra-kestra-1    | 2024-07-23 22:18:41,633 INFO  jdbc-queue-Execution_0 flow.pipPackagesDocker [namespace: company.team] [flow: pipPackagesDocker] [execution: 5hTbdEIo65dDeBhx2UtMBD] Flow completed with state FAILED in 00:00:03.262
kestra-kestra-1    | 2024-07-23 22:18:41,680 INFO  default-nioEventLoopGroup-1-6 io.kestra.webserver.access 2024-07-23T22:18:38.621Z | GET /api/v1/executions/5hTbdEIo65dDeBhx2UtMBD/follow HTTP/1.1 | status: 200 | ip: 10.0.0.1 | length: 665 | duration: 3058
```
This is the log from within the Kestra dashboard:
```
2024-07-23 15:18:41.415company.teampipPackagesDockerrun_python5hTbdEIo65dDeBhx2UtMBDCommand failed with code 1
2024-07-23 15:18:41.168[company.team](https://my.domain.com/ui/flows?namespace=company.team)pipPackagesDockerrun_python5hTbdEIo65dDeBhx2UtMBDexec /bin/sh: exec format error
2024-07-23 15:18:39.940company.team[pipPackagesDocker](https://my.domain.com/ui/flows/edit/company.team/pipPackagesDocker)run_python5hTbdEIo65dDeBhx2UtMBDProvided 1 input(s).
2024-07-23 15:18:39.904company.teampipPackagesDockerrun_python[5hTbdEIo65dDeBhx2UtMBD](https://my.domain.com/ui/executions/company.team/pipPackagesDocker/5hTbdEIo65dDeBhx2UtMBD)Provided 0 input(s).

```
My docker-compose.yaml

```
version: "3.8"
volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local
services:
  postgres:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: mysupersecretepostgrespassword
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 30s
      timeout: 10s
      retries: 10
  kestra:
    image: kestra/kestra:latest-full
    pull_policy: always
    # Note that this is meant for development only. Refer to the documentation for production deployments of Kestra which runs without a root user.
    user: root
    command: server standalone --worker-thread=128
    volumes:
      - ./kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment:
      KESTRA_CONFIGURATION: >
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: mysupersecretepostgrespassword
        kestra:
          server:
            basic-auth:
              enabled: true
              username: "myactualemail@sample.com" # it must be a valid email address
              password: mysecretkestrapasswordwhichisnotthis
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: https://my.domain.com/
    ports:
      #- "8080:8080"
      - :8080
      - :8081
    depends_on:
      postgres:
        condition: service_started
    networks:
      - default
      - docker-services
networks:
  docker-services:
    external: true
    name: docker-services
```
I used the same docker-compose (modified for the server domain/url) to run Kestra on a Debian VM running an intel 64bit processor and I'm able to successfully run Flows containing python scripts including the one referenced above. 

### Environment

- Kestra Version: 0.17.13
- OS: Docker-ce 5:27.1.1-1  on Ubuntu 22.04.4 LTS
- kernel 6.5.0-1023-oracle
- Platform: aarch64/ARM64 on Oracle Cloud Infrastructure Ampere A1 instance

**Comment by riyamustare** [comment] 2024-10-03 13:59
can you assign me this project would like to contribute!

**Comment by kushal9897** [comment] 2024-10-14 21:37
I would like to work on this

**Comment by Ben8t** [comment] 2024-10-15 07:14
@kushal9897 do you have access to Oracle Cloud Infrastructure Ampere A1 environment ? 
(the issue is related to _Platform: aarch64/ARM64 on Oracle Cloud Infrastructure Ampere A1 instance_)


@venturanc `/bin/sh: exec format error` seems like the image has been build on a different platform (https://stackoverflow.com/questions/73285601/docker-exec-usr-bin-sh-exec-format-error)

Can you try with an explitly build docker image on this ARM architecture ?
https://hub.docker.com/r/arm64v8/python/

**Comment by venturanc** [comment] 2024-10-15 20:11
Thanks, I thought I had tried earlier with an image that was cross platform and it didn't work, but using the following flow, I was able to execute python on the Ampere A1 instance (using the container image of arm64v8/python):

```
id: pipPackagesDocker
namespace: company.team

tasks:
  - id: run_python
    type: io.kestra.plugin.scripts.python.Script
    containerImage: arm64v8/python
    beforeCommands:
      - pip install requests kestra > /dev/null
    warningOnStdErr: false
    script: | 
      import requests
      import json

      response = requests.get("https://api.github.com")
      data = response.json()
      print(data)

```
Based on this, it seems like the default Kestra python image (for when a container is not specified) just needs to be built cross-platform?

**Comment by kushal9897** [comment] 2024-10-15 20:57
@Ben8t, I do not have access to the Oracle Cloud Infrastructure Ampere A1 environment

**Comment by Ben8t** [comment] 2024-10-16 08:11
@venturanc thanks for the double check. Yes I think this is not related to Kestra per se. The default `containerImage` used by Kestra in Python task is a generic one, it's up to the user to use one working with underlying infrastructure.
Closing the issue

**Closed as not planned by Ben8t** 2024-10-16 08:11 UTC
Labels: kind/cooldown, good first issue
