### ISSUE TITLE
Impossible to save new flow creation

### ISSUE THREAD

**Issue by st3v3lyrious** [kestra-io/kestra#3811] opened 2024-05-24 07:08 UTC
### Describe the issue

After creating a new flow, from the topology view, it is impossible to save the flow and navigate to the Editor tab, even after explicitly saving the flow.
See screenshots below:
<img width="728" alt="Screenshot 2024-05-24 at 08 58 49" src="https://github.com/kestra-io/kestra/assets/7113907/d1be365a-7ede-4780-8083-8bc7b2fe6417">
<img width="861" alt="Screenshot 2024-05-24 at 08 59 05" src="https://github.com/kestra-io/kestra/assets/7113907/52cceb81-15de-47ec-b06a-5b6c4905eb54">

### Environment

- Kestra Version: 0.16.6
- Operating System (macOS Sonoma 14.5/Docker Desktop v4.30.0)

**Comment by MilosPaunovic** [comment] 2024-05-30 07:24
Hi @st3v3lyrious, I'm trying to reproduce this but it's unsuccessful. Could you provide some more details about it, like the flow `yaml` from the one you tried to create or at least a screen recording of reproduction steps?

**Comment by MilosPaunovic** [comment] 2024-09-05 09:39
Hey @st3v3lyrious, is this still reproducible on the `0.18.4` version for you, as I can not create a reproduction of an sort.

**Comment by MilosPaunovic** [comment] 2024-09-09 10:28
@Ben8t Could you try to reproduce this issue - if unable, we can close it for now?

**Comment by smunteankestra** [comment] 2024-09-09 10:53
@MilosPaunovic could not reproduce as well

**Comment by Ben8t** [comment] 2024-09-09 12:03
I'm not able to reproduce too 🤔 
@st3v3lyrious can give us a screenshareing video please ? Otherwise, we'll close the issue as it seems to work now

**Closed as completed** 2024-09-09 12:39 UTC
Labels: area/frontend, kind/quick-win
