### ISSUE TITLE
[Regression] Execution API endpoint with wait=true no longer returns flow outputs

### ISSUE THREAD

**Issue by razuro** [kestra-io/kestra#5356] opened 2024-10-08 13:52 UTC
### Feature description

Propose the Execution API of:
`http://localhost:8080/api/v1/executions/{namespace}/{flow_id}?wait=true`

to have the same output as:
`http://localhost:8080/api/v1/executions/{execution_id}`

Without the query params `wait=true`, we'll need to do two API calls;
1. to trigger execution
2. to get execution result

It's only natural to have the final output result for `http://localhost:8080/api/v1/executions/{namespace}/{flow_id}?wait=true` as it waits for the process to complete, so we can have the final result

**Comment by Malaydewangan09** [comment] 2024-10-10 18:53
Hey @razuro, can I pick up this issue if it hasn't been solved yet?
Thanks!

**Comment by Ben8t** [comment] 2024-10-11 12:42
@Malaydewangan09 this is issue can be complex and need more discussion. We'll keep details up to date here soon.

**Comment by anna-geller** [comment] 2024-10-11 13:21
If you expose some outputs on the flow level and you add the wait true, then the flow outputs should be already displayed in the response, check the docs here https://kestra.io/docs/how-to-guides/synchonous-executions-api 

Additionally, soon, we will have a native feature allowing your end users to submit Executions via a Form and fetch results nicely in a dedicated UI, you can follow along here https://github.com/kestra-io/kestra/issues/5424

**Comment by razuro** [comment] 2024-10-11 15:49
Hi @anna-geller @Ben8t @Malaydewangan09 ,
Thanks for the quick response. Sorry for not being clear enough. The final output that I'm referring to, is the actual `outputs` in the flow. Please see this reproducer file:

```
id: demo
namespace: company

tasks:
  - id: nothing
    type: io.kestra.plugin.core.log.Log
    message: nothing
 
outputs:
  - id: result
    type: JSON
    value: |
      {
        "final": "output"
      }
```

If we trigger the `http://localhost:8080/api/v1/executions/company/demo?wait=true` API, the `{  "final": "output"  }` wasn't shown in the API response. But if we trigger the execution result, `http://localhost:8080/api/v1/executions/{execution_id}` 
you can find the `{  "final": "output"  }` response is there.

With this fix/enhancement, I was hoping the same consistency across these two API. Hope that clarifies. Is it possible to re-open this issue? Thanks

**Comment by anna-geller** [comment] 2024-10-13 12:33
You're right, it looks like a regression. It no longer works as described in the documentation. Thanks for pointing this out!

**Comment by anna-geller** [comment] 2024-10-13 12:36
for anyone who picks this up: flow outputs should be returned as described here https://kestra.io/docs/how-to-guides/synchonous-executions-api#synchronous-executions-api. Currently, only task run outputs are returned. This looks like a regression as it no longer works the same way as described in the docs

**Comment by razuro** [comment] 2024-10-15 01:16
Thanks @anna-geller! @Malaydewangan09 would you still be interested to pick this up?

**Comment by Malaydewangan09** [comment] 2024-10-15 10:00
@razuro @anna-geller  I'd be happy to give it a try and take this on.

**Comment by Malaydewangan09** [comment] 2024-10-17 14:11
Hey @razuro @Ben8t @anna-geller ,

I’ve been able to reproduce the flow outputs consistently whenever we trigger the execution, just like we get in the execution result. Now, the task run outputs are also being sent in the response.

I believe this is what we were aiming for to fix this issue, right?

**Comment by anna-geller** [comment] 2024-10-17 16:13
What we are aiming for is what is described in the linked docs page: when triggering an execution with wait=true, the flow outputs should we included. Currently, they are not included.

**Comment by Malaydewangan09** [comment] 2024-10-20 18:10
Hey @razuro @anna-geller
Can you check this PR once ?
Thanks!

**Comment by razuro** [comment] 2024-10-25 08:38
Will this be in v0.19.6?

**Comment by Ben8t** [comment] 2024-10-25 08:41
Yes, the PR is merged. You can find it already in kestra:develop if you want to test it (just wait a bit for the Docker image to be build and push)

**Closed as completed** 2024-10-25 08:41 UTC
Labels: area/backend

**Comment by MilosPaunovic** [comment] 2024-10-25 09:48
For it to end up in `0.19.6` we would need to add the commit to the necessary branch. Do you mind doing that also @Skraye, as you're familiar with the changes?

**Comment by Skraye** [comment] 2024-10-25 09:55
Its already done!
