### ISSUE TITLE
Type inconsistency between outputs and variables

### ISSUE THREAD

**Issue by vivane** [kestra-io/kestra#1659] opened 2023-06-28 20:47 UTC
### Expected Behavior

If the output is assigned to the variable then it is expected that they would have the same type and could be used in the same way.
For example, if output produces the JSON object then variable pointing to this output should also be the object. Or, if output produces the JSONizable string then variable should also be convertible to JSON object.

### Actual Behaviour

* Output is produced as a JSON object but variable pointing to it is not recognized as an object.
* Output is produced as a JSONizable string but variable pointing to it cannot be converted to JSON object.

### Steps To Reproduce

See the example flows...

### Environment Information

- Kestra Version: 0.9.5
- Operating System (OS / Docker / Kubernetes): Windows, Docker
- Java Version (If not docker):

### Example flow

[flows.zip](https://github.com/kestra-io/kestra/files/11899831/flows.zip)

* Flow "_test-variable-flow_" produces a result in form of JSON object.
* Being called from another flow - _test-variable-flow_ - this result is converted to the string.
* Being declared as variable this result is converted to... something which can not be properly used.

**Comment by loicmathieu** [comment] 2023-08-07 13:28
@vivane there is two separate issue here:

1. An output from a subflow (a flow triggered by a Flow task) arrives as a String, this is caused by the fact that we render the output of the subflow before copying them inside the Flow task. We must do this as subflow variables are not the same as flow variables.
2. The json function takes a string not a template, we have no choice here as we haven't access to flow variables inside a function.

**Comment by loicmathieu** [comment] 2023-08-08 13:29
@vivane both issues cannot be solved so I close it.

**Closed by loicmathieu** 2023-08-08 13:29 UTC
Labels: bug
