### ISSUE TITLE
Ci: kestra-io/validate-action is failing

### ISSUE THREAD

**Issue by mmmoli** [kestra-io/kestra#3272] opened 2024-03-13 11:52 UTC
### Describe the issue

Few weeks ago our CI started failing indefinitely.

## The error

```
/usr/bin/docker run --name ad7455f84d0a4aa3985d8889cc8f2406_144490 --label 658317 --workdir /github/workspace --rm -e "INPUT_DIRECTORY" -e "INPUT_RESOURCE" -e "INPUT_SERVER" -e "INPUT_USER" -e "INPUT_PASSWORD" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/htch/htch":"/github/workspace" 658317:ad7455f84d0a4aa3985d8889cc8f2406  "./apps/web/kestra/src/lib/flows/comms" "flow" "" "" ""
jakarta.validation.ValidationException: Exception extracting values using: io.micronaut.validation.validator.extractors.InternalValueExtractors$$Lambda$738/0x00007fe2[6](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:7)8d[7](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:8)f350@3a1f2a1
	at io.micronaut.validation.validator.DefaultValidator.visitContainer(DefaultValidator.java:1275)
	at io.micronaut.validation.validator.DefaultValidator.visitElement(DefaultValidator.java:1105)
	at io.micronaut.validation.validator.DefaultValidator.visitElement(DefaultValidator.java:104[8](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:9))
	at io.micronaut.validation.validator.DefaultValidator.visitElement(DefaultValidator.java:1033)
	at io.micronaut.validation.validator.DefaultValidator.visitProperty(DefaultValidator.java:[9](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:10)84)
	at io.micronaut.validation.validator.DefaultValidator.doValidate(DefaultValidator.java:953)
	at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:187)
	at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:166)
	at io.kestra.core.models.validations.ModelValidator.isValid(ModelValidator.java:25)
	at io.kestra.core.models.validations.ModelValidator.validate(ModelValidator.java:18)
	at io.kestra.cli.AbstractValidateCommand.lambda$call$4(AbstractValidateCommand.java:91)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.kestra.cli.AbstractValidateCommand.call(AbstractValidateCommand.java:88)
	at io.kestra.cli.commands.flows.FlowValidateCommand.call(FlowValidateCommand.java:23)
	at io.kestra.cli.commands.flows.FlowValidateCommand.call(FlowValidateCommand.java:10)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.kestra.cli.App.execute(App.java:71)
	at io.kestra.cli.App.main(App.java:51)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [logQueue] of class: io.kestra.core.services.TaskDefaultService

Message: No bean of type [io.kestra.core.queues.QueueInterface<io.kestra.core.models.executions.LogEntry>] exists for the given qualifier: @Named('workerTaskLogQueue'). 
Path Taken: new TaskDefaultValidator() --> TaskDefaultValidator.taskDefaultService --> TaskDefaultService.logQueue
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2181)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1672)
	at io.kestra.core.services.$TaskDefaultService$Definition.inject(Unknown Source)
	at io.kestra.core.services.$TaskDefaultService$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1750)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1672)
	at io.kestra.core.validations.validator.$TaskDefaultValidator$Definition.inject(Unknown Source)
	at io.kestra.core.validations.validator.$TaskDefaultValidator$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2751)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1813)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:877)
	at io.micronaut.validation.validator.constraints.DefaultConstraintValidators.findConstraintValidator(DefaultConstraintValidators.java:149)
	at io.micronaut.validation.validator.DefaultValidator.validateConstrains(DefaultValidator.java:1378)
	at io.micronaut.validation.validator.DefaultValidator.visitElement(DefaultValidator.java:1110)
	at io.micronaut.validation.validator.DefaultValidator.visitElement(DefaultValidator.java:1048)
	at io.micronaut.validation.validator.DefaultValidator.visitElement(DefaultValidator.java:[10](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:11)33)
	at io.micronaut.validation.validator.DefaultValidator.doValidate(DefaultValidator.java:943)
	at io.micronaut.validation.validator.DefaultValidator.propagateValidation(DefaultValidator.java:1302)
	at io.micronaut.validation.validator.DefaultValidator.visitElement(DefaultValidator.java:[11](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:12)15)
	at io.micronaut.validation.validator.DefaultValidator$1.validateContainerValue(DefaultValidator.java:[12](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:13)46)
	at io.micronaut.validation.validator.DefaultValidator$1.validateContainerValue(DefaultValidator.java:1266)
	at io.micronaut.validation.validator.DefaultValidator$1.indexedValue(DefaultValidator.java:1233)
	at io.micronaut.validation.validator.extractors.InternalValueExtractors.lambda$new$4(InternalValueExtractors.java:71)
	at io.micronaut.validation.validator.DefaultValidator.visitContainer(DefaultValidator.java:12[16](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:17))
	... 35 more
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.kestra.core.queues.QueueInterface<io.kestra.core.models.executions.LogEntry>] exists for the given qualifier: @Named('workerTaskLogQueue'). 
	at io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2787)
	at io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:307)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:[17](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:18)50)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:[21](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:22)[65](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:66))
	... [75](https://github.com/HTCH-app/htch/actions/runs/8253382373/job/22575067852#step:4:76) more
```

## My GH Workflow

```
name: Kestra CI/CD

on: [push]

jobs:
  # Start by validating all kestra resources
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate `app.htch.comms` flows
        uses: kestra-io/validate-action@v0.14.0
        with:
          directory: ./apps/web/kestra/src/lib/flows/comms
          resource: flow
```

### Environment

- Kestra Version: `v0.13.0-full` and `v0.15.5-full`
- Kestra Validate Action Version: `kestra-io/validate-action@develop` & `kestra-io/validate-action@v0.14.0`
- Operating System (OS/Docker/Kubernetes): Github Actions `ubuntu-latest`

**Comment by brian-mulier-p** [comment] 2024-03-13 12:37
Hello ! Can you compare your setup with the one [here](https://github.com/brian-mulier-p/test-validation) ? I'm unable to reproduce even with a CI setup :'( Maybe there is some docker image cache in your actions that prevent the latest image from being built and there was a bug in previous versions ?

**Comment by brian-mulier-p** [comment] 2024-03-13 12:40
Can you also provide the flows that are being validated ? Maybe try to validate a flow directory with simple flows before to make sure whether or not there is a bug in the action or one flow that is being validated makes the whole thing crash

**Comment by mmmoli** [comment] 2024-03-13 14:09
New PR with failing flow https://github.com/brian-mulier-p/test-validation/pull/1

**Comment by brian-mulier-p** [comment] 2024-03-18 10:27
Closing as it got fixed by [that](https://github.com/kestra-io/kestra/commit/d5dbff08390000fe8a7744c62bd6decbcc17c838)

**Closed by brian-mulier-p** 2024-03-18 10:27 UTC
Labels: bug
