### ISSUE TITLE
Log Level filter can overflow the button

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6093] opened 2024-11-25 18:33 UTC
on executions > logs page, when you have more than 2 digits, the close cross is outside of the box: 
![image](https://github.com/user-attachments/assets/098fb0fa-8a78-4276-a545-219ed19393f3)

**Comment by joaomateusmunuera** [comment] 2024-11-25 18:55
Hello, I would like to work in this issue if possible

**Comment by MilosPaunovic** [comment] 2024-11-25 19:59
Absolutely, go for it @joaomateusmunuera! 🚀

**Comment by MilosPaunovic** [comment] 2024-12-03 08:34
Hi, is there any progress on this @joaomateusmunuera?

**Comment by Piyush-r-bhaskar** [comment] 2024-12-04 16:34
Hey @MilosPaunovic 
I believe this has been fixed in https://github.com/kestra-io/kestra/issues/6218 it's a duplicate of https://github.com/kestra-io/kestra/issues/6093

**Comment by MilosPaunovic** [comment] 2024-12-04 16:55
You're absolutely right @Piyush-r-bhaskar, this issue is solved via https://github.com/kestra-io/kestra/pull/6224.

**Closed as completed by MilosPaunovic** 2024-12-04 16:55 UTC
Labels: area/frontend, good first issue
