### ISSUE TITLE
False failed hightouch flow

### ISSUE THREAD

**Issue by LingzheHUANG** [kestra-io/kestra#4354] opened 2024-07-17 14:17 UTC
### Describe the issue

Hello team,
I have noticed an issue with the execution of the Hightouch flow. For example, the result of the flow returns a "failed" status. But when looking at the execution log, there are no errors, the only difference between the success and failed tasks is just the last line; the failed tasks return "is now null."
However, when I checked the status of these tasks in Hightouch, they all succeeded. It seems to be a somewhat random error. Is it possible to resolve this issue?
Thank you in advance.

### Environment

- Kestra Version: 0.17.8
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):
<img width="1472" alt="Capture d’écran 2024-07-17 à 16 16 40" src="https://github.com/user-attachments/assets/247d6f44-1422-4847-b0f9-b00701460c8e">

**Comment by smunteankestra** [comment] 2024-07-29 09:04
Could you please share the full flow to reproduce? I mean Kestra flow and the Hightouch setup

**Comment by LingzheHUANG** [comment] 2024-07-29 13:38
```
id: hightouch_sync
namespace: xxx

tasks:
  - id: reverseETL
    type : io.kestra.plugin.core.flow.Parallel
    tasks : 
      - id: sync_customer
        type: io.kestra.plugin.hightouch.Sync
        token: xxx
        syncId: xxx

triggers : 
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow 
    conditions:
        - type: io.kestra.plugin.core.condition.ExecutionFlowCondition
          namespace: xxx
          flowId: dbt_daily_job
```
Above is the kestra flow, the objective is to push a customer information table in bigquery to klaviyo, I have no much idea which information do you need as hightouch setup.

**Comment by fhussonnois** [comment] 2024-08-01 15:33
Hi @LingzheHUANG, the task is marked as failed if a final state different from `success` is returned from the Hightouch's API. The ` "is now null."` log is because we receive a status unknown by the plugin. In Hightouch, is the task status exactly "success" or something else?

**Comment by LingzheHUANG** [comment] 2024-08-05 07:16
Hi @fhussonnois Thansk for explanation, I understand better. In Hightouch the task status is completed with errors.

**Comment by fhussonnois** [comment] 2024-08-06 09:32
Thank you for you answer @LingzheHUANG. Then, I suppose that returned status was not `success`.  

Here are the possible status returned from the Hightouch API: "disabled" "pending" "cancelled" "failed" "queued" "success" "warning" "querying" "processing" "reporting" "interrupted". 

I've updated the plugin with the missing ones. The fix will be available in the next Kestra release.

I'm closing this question, but feel free to reopen it if the problem persists.The next version will be released very soon.

**Closed as completed by fhussonnois** 2024-08-06 09:32 UTC
