### ISSUE TITLE
Debug Outputs has incorrect expression when opened

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#5884] opened 2024-11-12 12:30 UTC
### Describe the issue

When first opening the Outputs tab and no outputs are selected, Debug Outputs shows up with `{{ outputs. }}` which is invalid. It should instead say `{{ outputs }}`. Seems to do it on any flow you run because the first output is not selected correctly.

![Screenshot 2024-11-12 at 12 29 14](https://github.com/user-attachments/assets/c18c5bb9-5d6d-4102-8905-abc77a402642)

Example Flow that generated this behaviour:

```yaml
id: myflow
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

Another:
```yaml
id: deploy_if_true
namespace: company.team

inputs:
  - id: deploy
    type: BOOLEAN
    defaults: false

tasks:
  - id: code
    type: io.kestra.plugin.scripts.python.Script
    containerImage: ghcr.io/kestra-io/pydata:latest
    beforeCommands:
      - pip install kestra
    outputFiles:
      - processed_orders.csv
    script: |
      from kestra import Kestra
      import pandas as pd

      df = pd.read_csv('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv')
      df['order_category'] = pd.cut(df['total'],
                                    bins=[0, 50, 150, float('inf')],
                                    labels=['Small', 'Medium', 'Large'])
      df.to_csv('processed_orders.csv')

      category_counts = df['order_category'].value_counts()
      outputs = {
                  "Small": int(category_counts.get('Small', 0)), 
                  "Medium": int(category_counts.get('Medium', 0)),
                  "Large": int(category_counts.get('Large', 0))
                }
      Kestra.outputs(outputs)

  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.deploy == true }}"
    then:
      - id: s3_upload_discounts
        type: io.kestra.plugin.aws.s3.Upload
        region: eu-west-2
        bucket: oss-example
        key: "processed_orders.csv"
        from: "{{ outputs.code.outputFiles['processed_orders.csv']}}"
        accessKeyId: "{{ kv('AWS_ACCESS_KEY_ID') }}"
        secretKeyId: "{{ kv('AWS_SECRET_KEY_ID') }}"

```

### Environment

- Kestra Version: `develop` EE 1e8413d
- Kestra Version: `develop` OSS 0e2328c

**Comment by 5AIPAVAN** [comment] 2024-11-12 14:58
i would like to do this :-)
please assign this to me

**Comment by anna-geller** [comment] 2024-11-15 12:34
The first output is expanded by default — that's expected. What's unexpected is that the expression is showing only `outputs.` instead of full outputs expression `outputs.mytask.outputName`
![image](https://github.com/user-attachments/assets/f5aa2342-f60c-489e-b8c2-94086d0ee465)

Seems like regression introduced in PR to https://github.com/kestra-io/kestra/issues/5523

Reproducer flow:

```yaml
id: get_data
namespace: company.team

inputs:
  - id: data
    displayName: Select Data to Download
    type: SELECT
    values:
      - customers
      - employees
      - products
      - stores
      - suppliers
    defaults: customers

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/ion/{{ inputs.data }}.ion  

outputs:
  - id: data
    type: FILE
    value: "{{ outputs.extract.uri }}"
```

**Comment by 5AIPAVAN** [comment] 2024-11-18 09:22
Sorry i just unassigned this issue myself ( i am just unable to do this )

**Comment by MilosPaunovic** [comment] 2024-11-18 09:31
@wrussell1999 This should've been handled by [this PR](https://github.com/kestra-io/kestra/pull/5943), could you check to confirm?

**Comment by MilosPaunovic** [comment] 2024-11-18 09:36
Aahh, scratch that, my bad, not solved yet.

@ManojTauro as you've worked on Outputs section quite recently, would you like to tackle this one also?

**Comment by ManojTauro** [comment] 2024-11-18 10:29
Sure @MilosPaunovic. Please assign this to me.

**Comment by MilosPaunovic** [comment] 2024-11-18 10:33
Awesome, thanks! ❤️

**Comment by ManojTauro** [comment] 2024-11-24 23:34
Hi @MilosPaunovic, I really appreciate your help in this issue. I found out what exactly happening here. 
I see that when there are no children for a task, by default it's not getting selected even though `selectedValue` `ref` variable has the `task.value` in it.

I can update `expandedValue` to show the `{{ outputs.task_name }}` instead of `{{ outputs. }}` in the debug editor, which will fix this issue, but the task wouldn't be in selected state when there are no children. Users might get confused because of this.

Another approach would be to check `typeof expanded.value` if it's not `string` then just display `{{ outputs }}`. I know this is kind of an hacky solution though. Because I noticed that `expanded.value` will have a object type (Array to be specific) when there are no children for the task.

Also, I wonder why `expanded` variable is defined as `ref[]` when values stored in this variable are strings i.e `child.path`.

Please advice how should I proceed.

Thank you.

**Comment by MilosPaunovic** [comment] 2024-11-25 07:36
> I can update expandedValue to show the {{ outputs.task_name }} instead of {{ outputs. }} in the debug editor, which will fix this issue, but the task wouldn't be in selected state when there are no children. Users might get confused because of this.

This seems like an solid solution, we can go with it.

**Comment by ManojTauro** [comment] 2024-11-25 19:19
Hi @MilosPaunovic, I have created a PR. Please review.

**Comment by MilosPaunovic** [comment] 2024-12-04 07:44
Great work, as always. Thanks for this @ManojTauro! 🚀

**Closed as completed** 2024-12-04 07:44 UTC
Labels: area/frontend, good first issue
