### ISSUE TITLE
Replace the visual "Ready to see your flow in action?"

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3692] opened 2024-05-08 08:45 UTC
Replace this visual 

![image](https://github.com/kestra-io/kestra/assets/86264395/40ee8b0d-019f-4e59-a0f1-1a368d9c3214)

with this one https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=2769-38211&t=bEC03TlJQTlDP0RU-4 

(text TBD)

Reason: a lot of space here is wasted. We can use it to tell users more about kestra here - some ideas:

- point to the video library https://kestra.io/tutorial-videos
- embed a video tutorial showing how a user can **execute** their first flow https://www.youtube.com/watch?v=6TqWWz9difM 
- point to plugins or blueprints

**Comment by MilosPaunovic** [comment] 2024-10-09 13:45
This is how this page needs to look like:
![image](https://github.com/user-attachments/assets/bbcbc647-e6b7-4953-8a58-419befcdb0d2)

And this is the artwork image:
![image](https://github.com/user-attachments/assets/5db3723d-34dc-4394-9abf-397df96cc96f)

**Comment by MilosPaunovic** [comment] 2024-10-09 13:47
Hey @mounikaperi, as you've recently submitted [this PR](https://github.com/kestra-io/kestra/pull/5340), would oyu be interested in tackling this issue, as well, as it is quite similar to the one you've already solved?

**Comment by AbhishekCS3459** [comment] 2024-10-14 21:27
@MilosPaunovic can I go for this issue?

**Comment by mounikaperi** [comment] 2024-10-15 01:12
@MilosPaunovic if noone is working, I can take it up

**Comment by MilosPaunovic** [comment] 2024-10-15 06:14
Let's first check if @AbhishekCS3459 is going to work on in, if not, you can take over. otherwise, there are [plenty of other issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=label%3A%22good+first+issue%22
) to take your pick from.

**Comment by mounikaperi** [comment] 2024-10-15 06:32
Sure @MilosPaunovic

**Comment by AbhishekCS3459** [comment] 2024-10-16 07:25
@MilosPaunovic I am working on this.

**Comment by Ben8t** [comment] 2024-10-21 07:24
@AbhishekCS3459 did you succeed to make any progress on this :) ?

**Comment by MilosPaunovic** [comment] 2024-11-11 21:13
Hi @mounikaperi, are you maybe still interested and have a bit of time to tackle this one?

**Comment by AbhishekCS3459** [comment] 2024-11-12 03:16
@Ben8t let me update this with a pull request by today or tomorrow.

**Comment by MilosPaunovic** [comment] 2024-11-12 07:14
Hi @AbhishekCS3459, why don't we let @mounikaperi respond if she has the time for this, as you've been assigned to it a long time without any response. If she can't do it, you can try out again, or, you can take your pick at another issue from the [backlog](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) in the meantime.

**Comment by mounikaperi** [comment] 2024-11-12 07:30
@MilosPaunovic if everyone is okay, i can pick this up

**Comment by MilosPaunovic** [comment] 2024-11-12 07:52
It's all yours @mounikaperi!

@AbhishekCS3459 There are plenty more issues in need of contributors, so if you're still up for it, I'm sure you'll find something interesting [here](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22).

**Comment by mounikaperi** [comment] 2024-11-12 08:13
@MilosPaunovic 
can you please share the svg format of above image, I see it is in PNG format

Also can you please let me know where exactly this new page needs to be created?
In the Flows -> When I click on an Id -> in the overview page?
Currently this is how the Flows -> Overview page looks like

![image](https://github.com/user-attachments/assets/a02e0b60-249b-40f4-bb33-14b5222ff2dd)


You want me to replace this page?

**Comment by MilosPaunovic** [comment] 2024-11-12 08:25
The image in SVG format:
![Property 1=Variant4](https://github.com/user-attachments/assets/98df1a0f-8e9f-483b-a62a-1db3c079ad6f)

And that page needs to be changed (as it already exists), it's the `Home.vue` file, the section where we're showing this translation string `$t('homeDashboard.no executions')`.

**Comment by mounikaperi** [comment] 2024-11-12 08:47
@MilosPaunovic 
sorry to bother you but how do I reproduce this $t('homeDashboard.no executions') page in my local. When i navigate to flows -> dwh-and-analytics -> overview - I see the below page loading (which says - Looks like there's nothing here… yet! Adjust your filters, or give it another go!) instead of the one you have given.

![image](https://github.com/user-attachments/assets/8f004643-93c2-4ef9-81c2-299728b243e5)

**Comment by MilosPaunovic** [comment] 2024-11-12 09:02
You're absolutely right, I apologies for guiding you in the wrong direction. So, we need to amend the `kestra/ui/src/components/flows/Overview.vue` component, to show the desired page when the opened flow has no executions, intsead of the full dashboard with empty values we're showing now.

You can add you code directly to the `Overview.vue` component with the `v-if` condition whether to show it or the dashboard.

**Comment by mounikaperi** [comment] 2024-11-12 09:14
Sure. No problem
So basically the requirement is when the number of executions are 0 we will show our new page instead of the one now, if there is atleast 1 execution we will show the Dashboard.vue.

Will code. I will get back to you if I have any queries

**Comment by MilosPaunovic** [comment] 2024-11-12 09:18
Yes, exactly as you've described it!

**Comment by mounikaperi** [comment] 2024-11-13 09:48
@MilosPaunovic 
I was able to create the page and was able to link everything except Execute button logic

- This new page is displayed in 2 places:

Flows -> Overview (Particular FlowId not selected, overall view page)
- If no executions done for any of the flows, display the new page.
- Having Execute button here is of no use, because to execute we need to select a flow first and then execute it. At this step, because the user didn't select any id, we might have to disable the Execute button even if we keep it.

Flows -> Overview -> Selected one flowId 
- Second, where we select one particular flow, and if that flow doesn't have any executions run, this page will display, here we can have the Execute button and have it linked to the existing logic. But what I see is, at the top right corner there is already an Execute button. Having an Execute button again is duplicate work. 


Instead of putting an Execute button and linking it to the functionality again, can we get rid of this button and give a message to user to click on the Execute button at the top right corner. Because adding a duplicate Execute button- we will have to link to the Execute dialog open code again and pass flowId, namespace dispatch the event which is duplicate work and is taking a lot of time than estimated.

Just a thought, please do let me know your views.

Except this, rest all is ready

![image](https://github.com/user-attachments/assets/bb04fe80-79ab-4f35-b5eb-3b8fc943ec45)

**Comment by MilosPaunovic** [comment] 2024-11-13 10:01
Hi @mounikaperi,

I would say that we need this page shown only in second case, when the single flow is opened by is not executed yet.

About the `Execute` button, we need to keep it, per design, it's okay for now that is duplicated in the header. Also, on the note of design, could you try to get it a bit closer to the original image:

![image](https://github.com/user-attachments/assets/cd68b9b2-b198-41bb-a166-6bdfecd5d210)

Regarding backgrounds and similar things?

But it's been great work so far, definitely! 🚀

**Comment by mounikaperi** [comment] 2024-11-13 10:04
Sure @MilosPaunovic 
so when the flow is not selected, can I keep the original page as is

**Comment by MilosPaunovic** [comment] 2024-11-13 10:11
Yup!

**Comment by Piyush-r-bhaskar** [comment] 2024-12-12 17:19
Hi @MilosPaunovic,

Thanks for the opportunity 😍. Hopefully new PR will close this issue.

Thanks to you too @mounikaperi  for your effort and time 😊

**Comment by MilosPaunovic** [comment] 2024-12-13 10:49
Thanks so much for all the efforts here @mounikaperi & @Piyush-r-bhaskar, it's really appreciated! 🚀 

Closed via https://github.com/kestra-io/kestra/pull/6446.

**Closed as completed by MilosPaunovic** 2024-12-13 10:49 UTC
Labels: area/frontend, kind/quick-win, good first issue
