### ISSUE TITLE
Selection of displayed cols on the execution page 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6332] opened 2024-12-05 21:14 UTC
When we have moved to new filter, we removed the feature to display the cols we want. 
We need to read this features, useful for user. And we need to keep the trigger as visible by default as this is one is really important.

**Comment by MilosPaunovic** [comment] 2024-12-06 07:50
Duplicate of https://github.com/kestra-io/kestra/issues/6237.

**Closed as not planned by MilosPaunovic** 2024-12-06 07:50 UTC
Labels: area/frontend, kind/backport-needed
