### ISSUE TITLE
io.kestra.plugin.core.storage.Purge does not purge deleted executions and trigger logs

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#3961] opened 2024-06-07 17:02 UTC
### Issue description

I have a following flow:

```yaml
id: clean_system
namespace: system

tasks:
  - id: clean_up_everything
    type: io.kestra.plugin.core.storage.Purge
    endDate: "{{ now() }}"
    purgeExecution: true
    purgeLog: true
    purgeMetric: true
    purgeStorage: true
```

I get following output when I run it:

<img width="738" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/2578b179-d6d6-49ff-8b37-1b0c4dd58fd9">

It deletes execution but it does not delete all of the logs:

<img width="602" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/005f2db7-803a-4224-b8ac-08995d090562">

I've tried to specify namespace/flowId mentioned it these logs but it did not work.
I've using latest Kestra 0.17.1 in a standalone mode on Ubuntu VMs I've noticed similar behaviour on 0.16.x as well
Am I missing something?

Another potential problem is that when I delete a flow it's logs are still available in Logs page. Probably it works as intended but it would be nice to be able to purge logs that are no longer needed. Maybe you can add some button to do it on demand or a config option to control logs behaviour.

**Comment by anna-geller** [comment] 2024-06-07 17:58
Can you say what you are trying to purge and for what time interval? Keep in mind we also have a PurgeExecution task

**Comment by anna-geller** [comment] 2024-06-07 18:03
> purge logs that are no longer needed. 

We actually have that functionality. Right click on any logs and from the menu on the right you should see an option to delete that specific log  👍

**Comment by aku** [comment] 2024-06-07 18:18
Not sure where to find the menu (
Here's what I see:

<img width="1146" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/e728f968-28f8-4065-beb7-ce416e939bc2">

My problems is that I have triggers that produce thousands of executions. Each execution in turn produces several logs entires. I'd like to be able to do a regular clean up either manually or using time trigger. In this case I just execute the flow manually. Also, I'd like to be able to purge logs left over deleted flows

**Comment by aku** [comment] 2024-06-07 18:20
> Can you say what you are trying to purge and for what time interval? Keep in mind we also have a PurgeExecution task

I'm trying to delete all old entries ( endDate = now() ) for now. Everything (executions, storage) got deleted except logs. In a real-world scenario I would have several tasks to delete different objects with different time windows (e.g. delete triggered executions every 15 minutes, keep failed tasks info for 48 hours+ for analysis)

**Comment by aku** [comment] 2024-06-07 19:38
Another problem is that if you go to logs and click on some execution that was deleted Kestra will show a spinner for awhile then an error pops up

<img width="795" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/cc8f4a73-774b-4635-8dba-e7f4af4f185a">

**Comment by anna-geller** [comment] 2024-06-08 10:57
Interesting, thanks for that extra content. What if, instead of purging logs, you could not store them in the first place? If you add the property `logLevel: WARN` (set to WARN or ERROR level), only critical logs will be stored, while all INFO/DEBUG logs won't be captured on the backend.

To manually purge specific logs:

![image](https://github.com/kestra-io/kestra/assets/86264395/70bb3237-1050-4e69-80c9-e9f53f4fd468)

**Comment by aku** [comment] 2024-06-08 13:22
> Interesting, thanks for that extra content. What if, instead of purging logs, you could not store them in the first place? If you add the property `logLevel: WARN` (set to WARN or ERROR level), only critical logs will be stored, while all INFO/DEBUG logs won't be captured on the backend.
> 
> 
> 
> To manually purge specific logs:
> 
> 
> 
> ![image](https://github.com/kestra-io/kestra/assets/86264395/70bb3237-1050-4e69-80c9-e9f53f4fd468)
> 
> 

The thing is that executions are already deleted so I cannot access the UI page you mentioned. Also it would be quite daunting to delete logs one by one.

Can I use logLevel option per task/flow or it is a global setting that will affect the whole system?

Ideally, I would like to have following features:
* being able to delete logs via Purge task (even if corresponding flow/task/execution is already deleted 
* a button in Logs page to delete logs manually
* per task/flow option to suppress logs

**Comment by anna-geller** [comment] 2024-06-09 10:42
> Can I use logLevel option per task/flow or it is a global setting that will affect the whole system?

it's per task

 > being able to delete logs 

the Purge task is intended to purge data in bulk (e.g. data older than 2 weeks) to avoid cluttering database space.  for now, we don't offer selective delete of specific logs programmatically, so I'd recommend trying not to store the logs that you don't want to keep by using the logLevel option


> a button in Logs page to delete logs manually

you're right that it's missing, I opened an issue here https://github.com/kestra-io/kestra/issues/3964 


> per task/flow option to suppress logs

Totally feasible, you can leverage plugin defaults to set it for a specific task or all tasks in a flow - setting this will only store WARN level log for all tasks in this flow

```yaml
id: myflow
namespace: company.myteam

tasks:
  - id: print_status
    type: io.kestra.plugin.core.log.Log
    message: hello

pluginDefaults:
  - type: io.kestra
    values:
      logLevel: WARN
```

**Comment by anna-geller** [comment] 2024-06-09 10:43
using the above info, I think you know what to do, so I'll close the issue. feel free to ask via Slack if you have further questions: https://kestra.io/slack

**Comment by loicmathieu** [comment] 2024-06-10 16:05
@aku, may I ask for additional information to be sure there isn't something we didn't understand?

Did you use the Purge task or did you delete executions manually? Because by default, the purge task will delete related logs; if not, it's a bug.

**Comment by loicmathieu** [comment] 2024-06-10 16:08
And you purge very aggressively with `endDate: "{{ now() }}"` without specifying the list of states so executions currently running will also be purged.

I'll advise to set it to for ex `{{ now() | dateAdd(-1, 'HOURS') }}` and restrict the state to avoid purging running executions.

**Comment by aku** [comment] 2024-06-10 16:14
> @aku, may I ask for additional information to be sure there isn't something we didn't understand?
> 
> Did you use the Purge task or did you delete executions manually? Because by default, the purge task will delete related logs; if not, it's a bug.

I've deleted data using Purge task. What I was trying to say is that it does not delete logs for non-existing executions/tasks which is probably a bug because there is no other way to delete these logs. Moreover, if you click some some of the links in these logs you will get an error - corresponding execution is missing

**Comment by aku** [comment] 2024-06-10 16:17
> And you purge very aggressively with `endDate: "{{ now() }}"` without specifying the list of states so executions currently running will also be purged.
> 
> I'll advise to set it to for ex `{{ now() | dateAdd(-1, 'HOURS') }}` and restrict the state to avoid purging running executions.

I used now() only as an example. In a real-world scenario I will of course use filters and less agressive time range. 
Since I'm adopting Kestra at the moment  and do a lot of experiments  I need a way to easily clean the system from hundreds of executions/logs/etc.

**Comment by loicmathieu** [comment] 2024-06-10 16:23
>  it does not delete logs for non-existing executions/tasks

I don't understand what are those logs that are not linked to an execution/task?

**Comment by aku** [comment] 2024-06-10 16:41
> > it does not delete logs for non-existing executions/tasks
> 
> I don't understand what are those logs that are not linked to an execution/task?

They are linked to executions/tasks that were deleted with with their corresponding flow
Also, it seems that the Purge task ignores disabled flows logs

Steps to reproduce:
1) Create some flow
2) Run this flow 
3) Observe there are some logs related to this flow's tasks/execution
4) Delete the flow manually
5) Run Purge task (endTime == now()) - it will delete logs of existing flows/executions as expected
6) Logs from step 3 are still there

See example below - 923 logs cleaned, more than 3k logs remain

<img width="855" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/3623c923-c4ce-4d98-9840-e6eeff049b39">


<img width="359" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/9cbdf8a8-76d9-495c-be1e-5b6b25e2716a">

**Comment by loicmathieu** [comment] 2024-06-11 07:00
I re-openned it, we will have a look at purging correctly executions for deleted or disabled flows.

**Comment by loicmathieu** [comment] 2024-07-08 14:21
The issue is with deleted execution not deleted flow.

It can be solved in two ways:
- Improve the Purge task to also delete data from deleted executions
- Delete logs, metrics, storage when we delete an execution. But this may be a choice as people may want to delete an execution but keep the metrics for ex.

**Comment by loicmathieu** [comment] 2024-07-08 14:55
There is also an issue with Trigger logs that are not purged, it should be added to the Purge task with a boolean `purgeTrigger` to control it.

**Comment by aku** [comment] 2024-07-08 17:36
> The issue is with deleted execution not deleted flow.
> 
> It can be solved in two ways:
> 
> * Improve the Purge task to also delete data from deleted executions
> * Delete logs, metrics, storage when we delete an execution. But this may be a choice as people may want to delete an execution but keep the metrics for ex.

Regarding the second issue, I had a separate issue here https://github.com/kestra-io/kestra/issues/4199

**Comment by loicmathieu** [comment] 2024-07-10 08:48
Deleted executions are now purged, it will be backported on the next 0.17 release.

**Closed as completed** 2024-07-10 11:54 UTC
