### ISSUE TITLE
Create a dedicated "Stats & License" UI section (subpage of the Administration section)

### ISSUE THREAD

**Issue by quentin-js** [kestra-io/kestra#2566] opened 2023-11-20 12:53 UTC
### Issue description

In the same Grafana provides instance statistics and a high-level overview of the oss/ee features, can we:

**- create a new subpage of the administration section?**
... see this inspiration
![image (19) (1)](https://github.com/kestra-io/kestra/assets/46087775/c9a7d1c3-a814-40a8-b525-e1bd2a49c92e)
![Untitled (10)](https://github.com/kestra-io/kestra/assets/46087775/7f4a8c26-b91f-440f-aa32-66a5b4aacb03)

**- display the statistics from the usage API** (https://kestra.io/docs/api-guide/api-oss-guide#get-/api/v1/usages)
... or from any other telemetry system

**- add a licensing table**
...like the one under "compare all features" from this page: https://kestra.io/enterprise

**- add a "free trial" button**
...creating an overlay form (& re-using his one: https://kestra.io/contact-us)
... or redirecting directly to the contact-us webpage

**Comment by anna-geller** [comment] 2023-11-20 13:21
duplicate of https://github.com/kestra-io/kestra/issues/2565

**Closed by anna-geller** 2023-11-20 13:21 UTC
Labels: enhancement
