### ISSUE TITLE
Ensure we first kill an Execution in a RUNNING, CREATED or QUEUED state before deleting it

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2597] opened 2023-11-24 09:02 UTC
You can delete a running execution but in this case the execution is not killed so it is still running but you cannot access it anymore.

There are two solutions here:
- Forbid deleting a running execution, it should be killed before
- Kill deleted execution before deleting them (possibly with a warning popup first)

Keep in mind that this should be compatible with the mass action.

## Context

When a user tries to delete an Execution that is currently in progress (CREATED, QUEUED or RUNNING state), we should first KILL such Execution(s) before deleting it to avoid inconsistencies. 

For the user, the Execution can be viewed as deleted, but under the hood, we will initiate a KILL operation to avoid inconsistencies and zombie processes before _eventually_ deleting those executions.

**Comment by fhussonnois** [comment] 2024-05-07 09:18
@loicmathieu is this a duplicate of: https://github.com/kestra-io/kestra/issues/2651 ?

**Comment by loicmathieu** [comment] 2024-05-07 09:22
No, as in #2651 we still allow to delete a running execution, this issue can still occurs

**Comment by loicmathieu** [comment] 2024-05-07 09:22
But I'm not sure what we can do about it, I'll move it to later ...

**Comment by loicmathieu** [comment] 2024-08-07 07:48
Another example: it can lead to concurrency limit inconsistency as with the Kafka runner it will not impact the concurrency limit store.

**Comment by anna-geller** [comment] 2024-08-26 12:39
superseded by https://github.com/kestra-io/kestra/issues/4746

**Closed by anna-geller** 2024-08-26 12:39 UTC
Labels: bug, area/backend
