### ISSUE TITLE
Namespace File Timeout issue with S3 backend

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#2609] opened 2023-11-29 11:14 UTC
### Explain the bug

Namespace files show issue when internal storage is AWS S3. It raises timeout issues

![image](https://github.com/kestra-io/kestra/assets/46634684/5f8d74c1-b522-44b9-ab2a-dcf99d661c72)

### Environment Information

- Kestra Version: 0.13.x
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by brian-mulier-p** [comment] 2023-11-29 18:21
Yes I think that's a duplicate of another issue on S3 repo

**Closed by brian-mulier-p** 2023-11-29 18:21 UTC
Labels: bug
