### ISSUE TITLE
UI - Filter scroll bar behaviour is inconsistent

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#6338] opened 2024-12-06 09:05 UTC
### Describe the issue

```[tasklist]
### Interaction difficulty
- [ ] interacting with crosses of the filter are a bit tricky (while it's still possible) since the hovering box of the scroll bar seems to reach the center of the filter box 
``` 
![image](https://github.com/user-attachments/assets/d150a4c4-d62e-4076-93ab-92ae44f95384)
![image](https://github.com/user-attachments/assets/2b69cfb9-9050-49d6-92e6-4ea3fcb945c0)

```[tasklist]
### Inconsistent behaviour
- [ ] ![image](https://github.com/user-attachments/assets/09b2ce30-7bcf-4421-bcd9-152a5b0a2ee7) The scrollbar doesn't appear while the full filter isn't visible
- [ ] ![image](https://github.com/user-attachments/assets/67918e9b-88c1-4390-a2da-15e1a4045789) The scrollbar appear when not useful since the filter is already fully visible
- [ ] ![image](https://github.com/user-attachments/assets/e4571fd4-4420-4636-9cb1-8ed865692bb9) The scrollbar doesn't appear on some page (like the Flows tab) while it appears on other (like the Executions tab).
- [ ] ![image](https://github.com/user-attachments/assets/27ffa741-032c-4a6d-8ac2-65437729d44c) ![image](https://github.com/user-attachments/assets/0cca9b94-8907-4a9d-b642-e95e87249b97) ![image](https://github.com/user-attachments/assets/eeb00f60-1348-4f9a-ac74-84281af5516e) Zooming in/out make the scrollbar appear/disappear near randomly.
``` 

### Environment

- Kestra Version: 0.20.2
- OSS
- Docker compose debian
- Web access :
  - Firefox
  - Windows 10

**Comment by tejas2292** [comment] 2024-12-06 21:12
@ReLoutre can you provide exact steps to generate this situation? 
I tested with 
1) multiple browsers with multiple screens sizes. 
2) Keeping filters full/ keeping it empty
3) Both Flows and Executions pages
4) Zoom in and Zoom Out

I don't see a scrollbar there at all on filter.
![image](https://github.com/user-attachments/assets/b6a4f97e-5988-442e-960b-fa89eaa9070c)
![image](https://github.com/user-attachments/assets/8385bc07-4908-4098-a421-da461a53914e)
![image](https://github.com/user-attachments/assets/7a817240-7d08-4c6b-9986-5792a17b3f9a)
![image](https://github.com/user-attachments/assets/9ef4df50-8024-4fa9-99e2-58ffb1070bf9)


Only thing that i am not sure is kestra production version.

**Comment by ReLoutre** [comment] 2024-12-09 08:36
Hi @tejas2292,
Well, it's even more strange that some users has a scrollbar for the filters and some other do not.
Note : I just updated to 20.4 and the scrollbar is still there.

> kestra production version

That a flag i putted in the settings, nothing important i guess, but i you want to add one to test : see the screen.

![image](https://github.com/user-attachments/assets/4539afd3-683b-4e83-835c-b30d01cb036d)

I'm not sure what more to add to help someone reproduce, I'm not doing anything particular, I described it as clearly as possible precedently.

**Comment by ReLoutre** [comment] 2024-12-09 08:39
Perhaps, from what i see, most of the filter you tried of a very long size, did you tried with a shorter one, like in my examples ?

And from what i see on your screens, not having a scrollbar prevents you to see the full content of your filters, seems even more like a bug.

**Comment by ReLoutre** [comment] 2024-12-09 09:48
Tried on Microsoft Edge navigator :
Unable to get the scrollbar as well, the display of filters boxes aren't the same, they expands up to the right end of the screen instead of being collapsed to the left like with Firefox.

Firefox :
![image](https://github.com/user-attachments/assets/89caa84b-fc18-4918-8a6b-154b9fb519ff)

Edge :
![image](https://github.com/user-attachments/assets/de8613f2-30bf-4639-9b44-2576cd709a4b)


Tried on Chrome as well, display and "errors" are the same as in edge.

**Comment by MilosPaunovic** [comment] 2024-12-20 11:09
I could not reproduce this either, on any browser.
@Ben8t could you try, and, if unable, please close this one?

**Comment by Ben8t** [comment] 2024-12-23 08:32
can't reproduce either. closing for now; waiting for better reproducer

**Closed as not planned by Ben8t** 2024-12-23 08:32 UTC
Labels: area/frontend, good first issue
