### ISSUE TITLE
Upon deleting a flow it's name is not displayed correctly

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#6115] opened 2024-11-26 13:51 UTC
### Describe the issue

Same behaviour if user tries to **Disable** flow 

![image](https://github.com/user-attachments/assets/b7732513-ab3e-4776-b4f7-8d88481b1a15)

### Environment

- Kestra Version: develop - latest

**Comment by MilosPaunovic** [comment] 2024-11-26 13:54
Duplicate of https://github.com/kestra-io/kestra/issues/6113.

**Closed as not planned by MilosPaunovic** 2024-11-26 13:54 UTC
Labels: area/backend, area/frontend
