### ISSUE TITLE
Flows not filtered when navigating from Namespaces

### ISSUE THREAD

**Issue by KoenWindey** [kestra-io/kestra#5965] opened 2024-11-18 07:33 UTC
### Describe the issue

When navigating as follows: Namespaces (in menubar) -> mynamespace (from the available list) -> Flow (at the top) I would expect to only get a list of Flows for this particular namespace.

Instead I get an unfiltered list of all Flows. This seems like a bug with the Flow filtering in this particular instance.

![image](https://github.com/user-attachments/assets/ab41eeef-6f26-438b-b6c4-6819cebddee0)

### Environment

- Kestra Version: 0.19.9

**Comment by tabzzz1** [comment] 2024-11-18 08:21
Could you please assign it to me? This issue looks interesting, and I'd love to work on it.

**Comment by MilosPaunovic** [comment] 2024-11-18 08:26
@tabzzz1 I've just assigned other one to you. Why don't we work on closing that one, and after, you can take over this one if nobody else does it in the meantime.

**Comment by Malaydewangan09** [comment] 2024-11-18 08:36
@MilosPaunovic 
I would like to pick this up.
Thanks!

**Comment by MilosPaunovic** [comment] 2024-11-18 08:39
Yup, go for it @Malaydewangan09! 🚀

**Comment by Malaydewangan09** [comment] 2024-11-19 06:13
Hey @MilosPaunovic 
I checked this out.
We have a namespace filter prefix on the backend side, but it is not being sent from the frontend when we are navigating to flows from a namespace.

**Comment by Malaydewangan09** [comment] 2024-11-19 19:57
Hey @MilosPaunovic 
Initially, I assumed this was a backend issue.
but, since this is a frontend issue,
The frontend is not something I am very familiar with.
It would take me longer than usual to solve this, so I think someone else can take it up.
Thanks !

**Comment by Ben8t** [comment] 2024-11-20 06:56
@MilosPaunovic I'm changing to kind/backend tag; let me know if it's not the case

**Comment by Malaydewangan09** [comment] 2024-11-20 06:58
No, the namespace filter is handled in the backend; this is a frontend bug.

**Comment by MilosPaunovic** [comment] 2024-11-20 07:14
You're right @Malaydewangan09, that is a UI related issue, as the proper filtering parameters are not being sent, that's why the list is not filtered. And thanks for being aware of what your strong suits are, and what aren't, and for letting me know. Will unassign you here, but you can always pick up something that fits more into your area of expertise.

**Comment by Malaydewangan09** [comment] 2024-11-20 07:31
Thanks!
I will look into some backend issues.

**Comment by aabhas-sao** [comment] 2024-11-20 18:12
Hi @MilosPaunovic,
I would like to work on this issue. Please assign me. Able to reproduce the issue locally.

**Comment by MilosPaunovic** [comment] 2024-11-20 19:27
Absolutely, go for it @aabhas-sao! 🚀

**Comment by aabhas-sao** [comment] 2024-11-22 07:48
Hi @MilosPaunovic ,
I have made the changes and added namespace to the query filter. Please check  it's impact once to other areas of ui.

**Closed as completed** 2024-12-04 12:56 UTC
Labels: area/frontend, kind/quick-win, good first issue

**Comment by MilosPaunovic** [comment] 2024-12-04 13:03
Great work, thanks for the contribution @aabhas-sao! 🚀
