### ISSUE TITLE
UI Execution Overview doesn't correctly handle errors caused by wrong output types

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5744] opened 2024-11-01 15:22 UTC
### Describe the issue

Demo: https://share.descript.com/view/VtM2aaZFpNU

![image](https://github.com/user-attachments/assets/02947863-92f5-4af9-bd60-d1ffe443874d)

Reproducer:

```yaml
id: invalid_output
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.debug.Return
    format: this is a string, not a number

outputs:
  - id: invalid
    type: INT
    value: "{{ outputs.hello.value }}"
```

### Environment

- Kestra Version: develop

**Comment by prajyot004** [comment] 2024-11-01 16:33
@anna-geller can you please assign this issue to me I want to take on it

**Comment by MilosPaunovic** [comment] 2024-11-01 16:34
Go ahead @prajyot004! :rocket:

**Comment by Dhanushgowda2342** [comment] 2024-11-02 08:46
hello sir @MilosPaunovic 
myself dhanush
i am new to contribution
can you guide me to contribution
thank you

**Comment by Dhanushgowda2342** [comment] 2024-11-02 08:48
hlo myself dhanush
i am new to open source contribution
can anyone say which language is used for this issue

**Comment by MilosPaunovic** [comment] 2024-11-02 08:55
Hi @Dhanushgowda2342 

It's the change in `Vue.js` that's necessary for this issue, but @prajyot004 is already working on it. If you're looking to find issue to contribute to, first step would be to check [this](https://kestra.io/docs/getting-started/contributing#setup-to-work-without-building-the-backend-from-the-source-code) guide, and after, you can check out [this filtered list of good first issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and find something you think you can help with.

**Comment by Dhanushgowda2342** [comment] 2024-11-03 04:39
Thank you for your guidance sir
since i am a begineer i dont know nothing about kubernetes,but i wish to contribute ,can you give some suggestions and guide me in right directions.

**Comment by prajyot004** [comment] 2024-11-03 09:19
@MilosPaunovic do we have any community like discord, slack where I can  meet people who are working on this project ?
I tried the slack link but it is showing the link is expired.

**Comment by anna-geller** [comment] 2024-11-03 10:36
@prajyot004 can you refresh your page and try again? I'm sure the Slack link is working kestra.io/slack -- only transient issue can happen due to Slack invite quirks

**Comment by MilosPaunovic** [comment] 2024-11-03 10:46
@Dhanushgowda2342 There was no mention of Kubernetes, not really sure what do you mean by it. The setup instructions are on the link I've sent in the comment above, and when you start the project, you need to recreate steps using scenario Anna provided in the description of this issue.

**Comment by prajyot004** [comment] 2024-11-04 20:45
Hi @anna-geller @MilosPaunovic I need a help to solve this issue. The issue is quite complex. I found a conclusion on this that is when the user is executing the task task is executing successfully It is going from states created-> running -> success -> failed
I am not able to figure out after success why it is again turing it into failed .
```
{
    "id": "1qb1j1bTQ2B2sG5PiAFGB6",
    "namespace": "company.team",
    "flowId": "invalid_output",
    "flowRevision": 22,
    "taskRunList": [
        {
            "id": "3xTReNQZOAKwdIVByromMG",
            "executionId": "1qb1j1bTQ2B2sG5PiAFGB6",
            "namespace": "company.team",
            "flowId": "invalid_output",
            "taskId": "hello",
            "attempts": [
                {
                    "state": {
                        "current": "SUCCESS",
                        "histories": [
                            {
                                "state": "CREATED",
                                "date": "2024-11-04T20:38:37.455Z"
                            },
                            {
                                "state": "RUNNING",
                                "date": "2024-11-04T20:38:37.455Z"
                            },
                            {
                                "state": "SUCCESS",
                                "date": "2024-11-04T20:38:37.457Z"
                            }
                        ],
                        "duration": 0.002,
                        "endDate": "2024-11-04T20:38:37.457Z",
                        "startDate": "2024-11-04T20:38:37.455Z"
                    }
                }
            ],
            "outputs": {
                "value": "this is a string, not a number"
            },
            "state": {
                "current": "SUCCESS",
                "histories": [
                    {
                        "state": "CREATED",
                        "date": "2024-11-04T20:38:36.590Z"
                    },
                    {
                        "state": "RUNNING",
                        "date": "2024-11-04T20:38:37.454Z"
                    },
                    {
                        "state": "SUCCESS",
                        "date": "2024-11-04T20:38:37.458Z"
                    }
                ],
                "duration": 0.868,
                "endDate": "2024-11-04T20:38:37.458Z",
                "startDate": "2024-11-04T20:38:36.590Z"
            }
        }
    ],
    "labels": [
        {
            "key": "system.correlationId",
            "value": "1qb1j1bTQ2B2sG5PiAFGB6"
        }
    ],
    "state": {
        "current": "FAILED",
        "histories": [
            {
                "state": "CREATED",
                "date": "2024-11-04T20:38:36.161Z"
            },
            {
                "state": "RUNNING",
                "date": "2024-11-04T20:38:36.590Z"
            },
            {
                "state": "SUCCESS",
                "date": "2024-11-04T20:38:37.535Z"
            },
            {
                "state": "FAILED",
                "date": "2024-11-04T20:38:37.540Z"
            }
        ],
        "duration": 1.379,
        "endDate": "2024-11-04T20:38:37.540Z",
        "startDate": "2024-11-04T20:38:36.161Z"
    },
    "originalId": "1qb1j1bTQ2B2sG5PiAFGB6",
    "deleted": false,
    "metadata": {
        "attemptNumber": 1,
        "originalCreatedDate": "2024-11-04T20:38:36.161Z"
    },
    "scheduleDate": "2024-11-04T20:38:36.120Z"
}
```
This is the object that I am getting when the execution is completed. We can see the state history, but the error is not being passed in this response, which is causing the issue on the frontend. Could you please help me sort this out, or do you know someone on Slack with a better understanding whom I could connect with?
I have tried to debug this  for 3 days. I need some one who can give a direction to solve it.

**Comment by anna-geller** [comment] 2024-11-04 21:57
@fhussonnois might be able to provide guidance as he added the flow-level outputs in Kestra 🚀

**Comment by fhussonnois** [comment] 2024-11-05 13:37
When the outputs fail to render, the execution is marked as FAILED. The problem is that no error is associated with the execution for this scenario. Updating the java class [ExecutorService](https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/runners/ExecutorService.java#L399) seems to be sufficient :

Here is the required change in the `onEnd(Executor)` method:

```java
newExecution = newExecution
    .withState(State.Type.FAILED)
    .withError(ExecutionError.from(e));
```



Here is the UI behaviour:

![kestra-invalid-outputs](https://github.com/user-attachments/assets/513353c0-ae38-43c4-a8df-e5941fa86a27)

@prajyot004 could you please do the change and provide a PR for that ? Thank you very much ;)

**Comment by prajyot004** [comment] 2024-11-05 19:08
Thank you, @fhussonnois, @anna-geller, and @MilosPaunovic, for your support and responses. @fhussonnois, I especially appreciate your guidance.

I would love to contribute more to this repository. This is my second contribution, and I'm happy to work on the issues you assign. Although I'm a beginner with this repo, working on this issue has led me to review many files, which has helped me gain a better understanding of the project.

**Comment by MilosPaunovic** [comment] 2024-11-05 20:50
Thanks for this contribution; we're lucky to have community members like yourself @prajyot004! 🚀 

I'll check the PR for this issue in the next few days and get back to you, in the meantime, you can take your pick from [this filtered list of good first issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and chose something you think you can help us with.

**Closed as completed** 2024-11-07 08:04 UTC
Labels: area/frontend, good first issue
