### ISSUE TITLE
Labels in execution page are not shown

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5879] opened 2024-11-11 10:03 UTC
### Describe the issue

Having this Flow::

```
id: autotest_14163083-2e98-4660-8f7a-58f9fe6433fd
namespace: autotest_14163083-2e98-4660-8f7a-58f9fe6433fd

labels:
  song: never_gonna_give_you_up
  artist: rick_astley

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "Hello, {{ missing_variable }}!"
```

no labels are returned in execution page

![image](https://github.com/user-attachments/assets/4fff6987-c4eb-4b2a-bd2c-d6022f996b1b)

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment] 2024-11-12 09:14
Could not reproduce this issue, labes are present, as expected. @Ben8t Could you try on your side?

![image](https://github.com/user-attachments/assets/440e239a-107f-470c-9ccb-c20c40286f9f)

**Comment by Ben8t** [comment] 2024-11-12 09:19
Yes, same here, not able to reproduce. Closing for now, @smunteankestra can you detail maybe a specific setup 🤔 ?

**Comment by smunteankestra** [comment] 2024-11-12 10:02
strange guys, I can reproduce - the labels are present inside the execution details but not on all executions page
Still let's leave it closed since it;'s not reproducible on your sides :) 

![image](https://github.com/user-attachments/assets/8422d346-3668-4508-929b-4808f7d8a676)

![image](https://github.com/user-attachments/assets/3a965d9c-079b-462e-b146-46d8bb8a6696)

**Comment by MilosPaunovic** [comment] 2024-11-12 10:06
Can you reproduce that with manual testing?

**Comment by Ben8t** [comment] 2024-11-12 10:08
On OSS preview everything looks fine 🤔 Maybe your develop version is a bit old

**Comment by smunteankestra** [comment] 2024-11-12 10:27
please try on EE

**Comment by Ben8t** [comment] 2024-11-12 10:31
Indeed, it's happening in EE. Reopening and moving the issue in the corresponding repo 👍 thanks !

**Comment by MilosPaunovic** [comment] 2024-11-12 10:34
Actually, just checked, it's the same component used in EE as it is on OSS, also, labels are properly returned from the endpoint. But, we'd need to wait for proper deployment of EE so we can check if it's amended.

**Comment by MilosPaunovic** [comment] 2024-11-18 10:43
After a bit of digging, on the EE side, the `configs.hiddenLabelsPrefixes` without anything set up for that functionality, is returning empty string as the only value (`hiddenLabelsPrefixes: [""]`), which is basically ignoring everything with the current filtering method on the UI.

Is that the expected behavior @loicmathieu?

**Closed as completed** 2024-11-18 12:56 UTC
Labels: area/backend, area/frontend
