### ISSUE TITLE
New plugin - AWS Kinesis

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1500] opened 2023-06-12 15:23 UTC
### Feature description

Add AWS Kinesis plugin

**Comment by anna-geller** [comment] 2023-07-25 19:51
Example scenario: consume streams from a Kinesis Data Stream, filter/manipulate data and publish into another Kinesis stream using a produce(r) task

**Comment by anna-geller** [comment] 2023-09-08 00:06
closing as duplicate of https://github.com/kestra-io/plugin-aws/issues/43

**Closed by anna-geller** 2023-09-08 00:06 UTC
Labels: plugin
