### ISSUE TITLE
Unrelated logs displayed on the trigger page

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#4913] opened 2024-09-13 07:25 UTC
### Describe the issue

When adding a trigger (in this case a webhook), logs of a previous execution of the flow are displayed, which are 3 days older than the trigger and totally unrelated
![image](https://github.com/user-attachments/assets/c32a5086-4f82-4968-b3a3-05128a142299)

### Environment

- Kestra Version: 0.18.6

**Comment by MilosPaunovic** [comment] 2024-09-13 07:35
@Skraye Could that be due to this commit https://github.com/kestra-io/kestra/commit/6bf61884523e627a7ca9d52c89638909bc5f752a?

**Comment by Skraye** [comment] 2024-09-13 07:47
@MilosPaunovic Reverting the commit do not fix the issue, so I don't think

**Comment by anna-geller** [comment] 2024-09-15 18:54
seems like a duplicate of this https://github.com/kestra-io/kestra/issues/4791 -- if not, reopen

**Closed as not planned by anna-geller** 2024-09-15 18:54 UTC
Labels: area/backend
