### ISSUE TITLE
Custom Blueprints page doesn't load properly

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4809] opened 2024-09-03 14:10 UTC
### Describe the issue

Related to #4729.

Now there is no internal server error, but clicking on Custom Blueprints doesn't refresh the component to load the custom blueprints. 

![blueprints](https://github.com/user-attachments/assets/834ad0db-1d96-46c0-b0a7-7f3753e8f775)

### Environment

- Kestra Version: 0.18.4
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by MilosPaunovic** [comment] 2024-09-09 11:24
This one seems to be fixed in the meantime by one of the previous commits on this topic, as I can not reproduce it on latest `develop` branch. Could you try @Ben8t?

**Comment by Ben8t** [comment] 2024-09-09 12:08
Yes indeed seems to work now (both in main blueprint tab or within flow editior). I'm closing the issue

https://github.com/user-attachments/assets/7ee0bcb5-87af-4ad9-8149-8aa6837a6a96

**Closed as completed by Ben8t** 2024-09-09 12:08 UTC
Labels: kind/quick-win, kind/customer-request
