### ISSUE TITLE
Gantt view doesn't refresh after replay

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5759] opened 2024-11-04 08:58 UTC
### Describe the issue

Cyril was doing a demo, and within 5 minutes after the task run succeeded after Replay, the Gantt view bar didn't change to green. Perhaps the Gantt UI page needs to refresh automatically more often?

![image](https://github.com/user-attachments/assets/f03cb08e-a35d-48d0-b1ad-29dcafdfac47)

### Environment

- Kestra Version: develop

**Comment by bharateshwq** [comment] 2024-11-04 17:53
I'd like to work on this!

**Comment by MilosPaunovic** [comment] 2024-11-04 19:33
I've assigned you to another issue @bharateshwq, why don't we close that one first and then you can tackle this one.

**Comment by ManojTauro** [comment] 2024-11-05 11:32
Hi @MilosPaunovic, I'd like work on this. Could you please assign this to me?

**Comment by MilosPaunovic** [comment] 2024-11-05 11:33
Absolutely, go for it @ManojTauro! 🚀

**Comment by ManojTauro** [comment] 2024-11-07 10:43
Hi @MilosPaunovic I have created a PR for this issue. Please review and also let me know if you have any feedback for me.

Thanks

**Comment by MilosPaunovic** [comment] 2024-11-14 07:44
Hey @Ben8t, could you share a flow which will help us test this in the best way?

**Comment by Ben8t** [comment] 2024-11-14 07:50
Basic flow, just have to hit replay and not refresh to see that the task bar stay blue instead of moving to green.

```yaml
id: test
namespace: company.team

tasks:

 - id: task1
   type: io.kestra.plugin.core.log.Log
   message: "Hello"
```

![image](https://github.com/user-attachments/assets/fee1f399-2e8b-4bcc-8500-7406411b7fd8)

**Comment by MilosPaunovic** [comment] 2024-11-14 08:04
Hmm, a bit weird, I cannot reproduce the that issue with the flow from above without the fix. Could you maybe do a short screen recording, to check if I'm doing something wrong here @Ben8t?

**Comment by Ben8t** [comment] 2024-11-14 08:10
yep, here it is https://share.descript.com/view/Krjsw1FbIe6

**Closed as completed** 2024-11-14 08:14 UTC
Labels: area/frontend, kind/quick-win, good first issue

**Comment by MilosPaunovic** [comment] 2024-11-14 08:15
Ahh, my bad, was replaying from the `Overview` page instead directly from the `Gantt` one, thanks @Ben8t. And also, big thanks to @ManojTauro, I've just merged his PR which resolves this issue! 🚀

**Comment by MilosPaunovic** [comment] 2024-11-14 13:27
A note that I've pushed a commit that fixed this issue to the branch we're using for `0.19.x` releases, so it'll end up there as part of the next maintenance cycle.

Also, @ManojTauro, you've done what we developers usually just dream of - closed three separate issues (https://github.com/kestra-io/kestra/issues/5759, https://github.com/kestra-io/kestra/issues/5503, https://github.com/kestra-io/kestra/issues/3171) with one commit (https://github.com/kestra-io/kestra/pull/5829)! 🏆

Great job there, looking forward to count how many of them you can close with the next `PR`! 😄

**Comment by ManojTauro** [comment] 2024-11-14 20:22
Thank you so much for your kind words, @MilosPaunovic. I appreciate it. I'm looking forward to picking up more issues.
