### ISSUE TITLE
Change task run value color to white to make it readable in the ForEach task Gantt and Logs views

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5445] opened 2024-10-14 07:46 UTC
### Describe the issue

![image](https://github.com/user-attachments/assets/1f59675c-78d6-4618-9025-bfa3c7a9d6f7)

![image](https://github.com/user-attachments/assets/d8e7fd85-6693-4d5b-9968-65d6ffea63ba)

to reproduce, create two flows and run the first one:

```yaml
id: file_output_parent_concat_foreach_batch_1
namespace: company.team

  outputs:
    - id: myoutput
      type: FILE
      value: "{{ outputs.jsonata.uri }}"

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv', header=True);
    store: true

  - id: for_each_item
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ outputs.extract.uri }}"
    batch:
      rows: 1 # TBD annoying that it cannot be passed from inputs
      # https://github.com/kestra-io/kestra/issues/5442
    namespace: company.team
    flowId: file_output_child
    wait: true
    transmitFailed: true
    inputs:
      json_file: "{{ taskrun.items }}"

  - id: ion_to_json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.for_each_item_merge.subflowOutputs }}"
    newLine: false

  - id: merge
    type: io.kestra.plugin.core.storage.Concat
    files: "{{ read(outputs.ion_to_json.uri) | jq('map(.myoutput)') | flatten }}"
    separator: "\n"

  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    allowFailure: true
    description: this will fail with Unable to read the file 'kestra:///....ion' as it didn't belong to the current execution
    values: "{{ read(outputs.ion_to_json.uri) }}"
    tasks:
      - id: log
        type: io.kestra.plugin.core.log.Log
        allowFailure: true
        message: "{{ read(json(taskrun.value).myoutput) }}"
```

child flow:

```yaml
id: file_output_child
namespace: company.team

inputs:
  - id: json_file
    type: FILE

tasks:
  - id: read_raw_ion_file
    type: io.kestra.plugin.core.log.Log
    message: "{{ read(inputs.json_file) }}"

  - id: jsonata
    type: io.kestra.plugin.transform.jsonata.TransformItems
    from: "{{ inputs.json_file }}"
    expression: |
      {
        "id": id,
        "name": data.Color & ' ' & name
      }
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by ssparser** [comment] 2024-10-14 09:37
hey @anna-geller can you assign this task to me.

**Comment by mithindev** [comment] 2024-10-14 12:14
@MilosPaunovic Could I work on the issue of changing the task run value color to white for better readability?

**Comment by MilosPaunovic** [comment] 2024-10-14 12:15
Absolutely, go for it! :rocket:

**Comment by Daulat1249** [comment] 2024-10-14 22:06
I think we can add a "color" attribute within the "log" task like this :   
  - id: log  
    type: io.kestra.plugin.core.log.Log  
    allowFailure: true  
    message: "{{ read(json(taskrun.value).myoutput) }}"  
    color: white
-> can add this inside the parent file 
-> Q: I'm not sure about this so can you just help me with do i have to something more in it?
@MilosPaunovic

**Comment by anna-geller** [comment] 2024-10-14 22:56
@Daulat1249 this issue is purely a frontend display/design issue, no need to adjust the Log task 👍

**Comment by Dheerajr444** [comment] 2024-10-15 12:50
Hi @anna-geller unable to reproduce this issue as you say I create two flows and run the first one this show an error
 `Unable to find `subflowOutputs` used in the expression `{{ outputs.for_each_item_merge.subflowOutputs }}` at line 1`

**Comment by anna-geller** [comment] 2024-10-15 15:24
the flow here is just an example, what matters for the issue is the task run name color

**Comment by MilosPaunovic** [comment] 2024-10-24 12:27
Closed via https://github.com/kestra-io/kestra/pull/5642.

**Closed as completed by MilosPaunovic** 2024-10-24 12:27 UTC
Labels: area/frontend, kind/quick-win, good first issue
