### ISSUE TITLE
Render expression does not work

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4405] opened 2024-07-23 15:29 UTC
### Describe the issue

Opening render expression for the first time in an execution (nothing is displayed when saved):
![Screenshot 2024-07-23 at 16 28 25](https://github.com/user-attachments/assets/edfa2d6e-b1fc-4688-8aa0-97f8481ab3b8)

After changing to `{{ outputs }}` and saving and then back to `{{outputs.extract }}`
![Screenshot 2024-07-23 at 16 28 38](https://github.com/user-attachments/assets/6f4cebae-82b7-4b07-9946-6521dbcba5ac)

### Environment

- Kestra Version: 0.18 Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment] 2024-07-23 17:15
@wrussell1999 Could you provide the flow you've used for this, it will be much easier to pinpoint the problem.

**Comment by wrussell1999** [comment] 2024-07-24 15:36
@MilosPaunovic this blueprint: https://kestra.io/blueprints/getting-started/223-getting-started-with-kestra-a-data-engineering-pipeline-example

**Comment by johnkm516** [comment] 2024-07-31 04:27
@MilosPaunovic 

Having the same issue. Doesn't seem to matter which flow, in my case I have a flow with an HTTP Request and the render expression doesn't work if I do 
```{{outputs}}```
or 
```{{inputs}}```
or 
```{{outputs.httpRequest.body}}```

My version is latest 0.17.16 release. 
I tested it out a bit more, it seems if you do something like ```{{outputs.httpRequest.body | length }}``` first and then try rendering ```{{outputs.httpRequest.body}}``` again it works, but then if you try to render any expression that causes a pebble template error and then try to render anything afterward it doesn't work again.

**Comment by MilosPaunovic** [comment] 2024-07-31 09:08
This seems to be sorted out now; I can't seem to reproduce it anymore after work on other issues related to rendering expressions (https://github.com/kestra-io/kestra/commit/1425fb872ed80c2f06720fc920409b742f49ebaf and https://github.com/kestra-io/kestra/commit/f0f4b20586097b9325ad81de3d2fbacab6b7740a). 

Can you test it one more time when you get the chance @wrussell1999 or @anna-geller, just to be on the safe side?

As for @johnkm516, this is related to our upcoming `0.18.0` release which is very close, see [this LN post](https://www.linkedin.com/posts/kestra_sneak-peek-into-our-next-release-were-activity-7223695503228637185-mvie) for more details on outputs.

**Comment by anna-geller** [comment] 2024-07-31 11:01
yup, works on `develop` image out of the box now 

@johnkm516 we'll release Kestra 0.18.0 next Tuesday so the fix will be released very soon, now in a new, nicer Outputs UI :) hope that works for you?

![image](https://github.com/user-attachments/assets/e82a2f5f-0406-4449-bef7-c3b02ac287ae)

**Closed as completed by anna-geller** 2024-07-31 11:01 UTC
Labels: area/frontend
