### ISSUE TITLE
Blueprints bottom of the page improve design

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#3978] opened 2024-06-10 12:39 UTC
### Feature description

At the Blueprints page a bit more space at the bottom of the page would be nice to add, check screenshot 

<img width="1778" alt="image" src="https://github.com/kestra-io/kestra/assets/171780240/d2f7a797-22fe-4155-b27f-d240fbb764c7">

**Comment by MilosPaunovic** [comment] 2024-06-10 13:33
Duplicate of #3981

**Closed as completed by MilosPaunovic** 2024-06-10 13:33 UTC
