### ISSUE TITLE
Namespace dropdown is empty while adding roles to groups

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3413] opened 2024-03-28 08:14 UTC
### Describe the issue

1. Go to Groups.
2. Create a group, or select an existing one.
3. Go to Roles tab, and click on Add.
4. Select a Role from the dropdown.
5. Click on Namespace dropdown.
6. Even when there are multiple namespaces available, the dropdown is empty.

### Environment

- Kestra Version: 0.15.8
- Operating System (OS/Docker/Kubernetes): Cloud
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment] 2024-03-28 09:49
I cannot reproduce it for now; maybe you can send some screenshots?

![image](https://github.com/kestra-io/kestra/assets/86264395/b15880dc-7769-4ac1-97cf-8b335924ad9b)

**Comment by shrutimantri** [comment] 2024-03-28 12:22
Here is the screen recording link: https://drive.google.com/file/d/1Zeoeg7SFG4flVEqw7jb_NpGgt3EkUH3D/view?usp=drive_link

**Comment by anna-geller** [comment] 2024-03-28 14:57
ok I see, you haven't created any namespaces, that's why no namespaces are listed in the dropdown. 

![image](https://github.com/kestra-io/kestra/assets/86264395/c3136b5a-878c-4226-9aa3-bcfd42f6a901)

Once you create them, they will be available in the dropdown. I'll close the issue because we are aware the UX here is not the best and we're tracking this in other issues

**Closed by anna-geller** 2024-03-28 14:57 UTC
Labels: bug
