### ISSUE TITLE
[UI] Make font size for flow logs adjustable

### ISSUE THREAD

**Issue by n0obHere** [kestra-io/kestra#6057] opened 2024-11-22 15:55 UTC
### Feature description

Hello,

Currently the font size for the flow logs is not adjustable, and the default font size feels too small and is quite straining on the eyes. I think it should be adjustable same as how the editor font family and size can be adjusted in the settings.

Thanks

**Comment by AdityaSrivastava185** [comment] 2024-11-22 18:39
Hello , can I work on this , I would like to work and solve the issue , please assign this to me

**Comment by MilosPaunovic** [comment] 2024-11-22 19:10
Hey @AdityaSrivastava185, we're not sure when or if we want to implement this.

May I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by AdityaSrivastava185** [comment] 2024-11-23 04:19
Sure @MilosPaunovic , thank you , I will definitely check out the list for issues

**Comment by anna-geller** [comment] 2024-11-25 10:04
@MilosPaunovic I think the request is reasonable, we can add a Setting to adjust the font size for logs 

We can move the Editor Font Family up to the same row as Chart Color Scheme and add the Logs font Size next to Editor Font Size in the same row
![image](https://github.com/user-attachments/assets/dfd0441d-7c46-4d7a-8af2-4cb0a40fbfff)

@AdityaSrivastava185 if you are interested, we would love a PR for it 🫶

**Comment by AdityaSrivastava185** [comment] 2024-11-25 13:23
Thank you @anna-geller , I will  definately work on this issue 
Thank you for assigning me 🙂

**Comment by AdityaSrivastava185** [comment] 2024-11-26 20:35
Hello @anna-geller, I am currently working on this issue but am having trouble locating the file path where the changes need to be made. Could you please provide a reference or the correct file path for the implementation? Thank you 😃

**Comment by MilosPaunovic** [comment] 2024-11-27 07:10
What have you tried so far @AdityaSrivastava185?

**Comment by AdityaSrivastava185** [comment] 2024-11-27 07:32
I've reviewed the related sections of the codebase, specifically the settings related to Editor Font Family, Chart Color Scheme, and Editor Font Size. I’ve also checked how new settings are typically added to ensure consistency. However, I’m having trouble fully understanding how the Logs Font Size setting should integrate into the UI and where exactly in the codebase this adjustment should be made.

If there’s any guidance on where to focus or examples of similar settings being implemented, it would be really helpful to get me unstuck!
Thank you

**Comment by MilosPaunovic** [comment] 2024-11-27 07:36
`kestra/ui/src/components/settings/BasicSettings.vue` is the component where yo would place the font selector, and you can use `Vue Devtools` as inspector to locate the component where you need to take that into account.

**Comment by AdityaSrivastava185** [comment] 2024-11-27 07:40
Thank you for the guidance! I'll check out , This helps a lot

**Comment by Piyush-r-bhaskar** [comment] 2024-12-30 08:43
I had a PR for this & was going to link but just checked one is already linked by @rajatsingh23 Y'day and seems will solve the issue. 😁

**Closed as completed** 2024-12-30 09:40 UTC
Labels: area/frontend, good first issue

**Comment by MilosPaunovic** [comment] 2024-12-30 09:41
Thanks for this @rajatsingh23! 🚀 

If you add a comment here, I'll be able to assign this issue to you; otherwise, GitHub won't let me do it.

**Comment by rajatsingh23** [comment] 2024-12-30 09:44
Can I work on this? 😁

**Comment by anna-geller** [comment] 2025-01-06 09:11
thx for contributing @rajatsingh23 - confirmed the issue is done
