### ISSUE TITLE
[TBD] Add an array input type

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2153] opened 2023-09-20 17:07 UTC
### Feature description

Ludo briefly mentioned it, details TBD

**Comment by tchiotludo** [comment] 2023-09-20 17:09
duplicate of https://github.com/kestra-io/kestra/issues/771

**Comment by anna-geller** [comment] 2023-09-20 17:09
sorry, thx

**Closed by tchiotludo** 2023-09-20 17:09 UTC
Labels: enhancement
