### ISSUE TITLE
Killing WorkerTask can lead to infinite Killing

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#309] opened 2021-03-25 10:42 UTC
There is 2 cases : 
- executor don't know the execution (remove or prune), it will do nothing (no join on KTable)
- no worker are executing the tasks, no one will respond to executor 

We need to deal this case especially the worker one that seems to be more frequent than the others. 
- Maybe all worker must respond not for me and if all is reponding I don't know, killed the execution ?
- Maybe a timeout for the worker response and force killed ? 
- Maybe all worker must send a periodic state off current task to executor that can help me detect zombie tasks

**Comment by loicmathieu** [comment] 2023-05-25 12:29
The root cause of the issue must be solved if possible, instead of implementing something complicated.

So we must first try to fix as many issues as possible on the executor and worker side and only implement a more complex behavior if it still occurs.

We currently have a bunch of fixes and improvements on Executor and Worker so I think the best is to wait a little to see if it didn't fix most of the case where killing a worker task didn't work.

**Comment by tchiotludo** [comment] 2023-05-25 13:22
We don't have choice to find a proper solution on that point. 
It's really easy to have the issue, due to multiple race conditions. 
Maybe a first simple implementation will be a timeout to have a flow killed properly (by a response of a worker), if not, continue the process. It will cover 80 / 20 of the cases

**Comment by loicmathieu** [comment] 2023-06-23 14:54
Another idea would be to implements a fire and forget solution:
- Move the execution state to killing
- Send all worker a killing execution event
- Effectively kill the execution without waiting for the worker to send a killed event

This needs to be checked with various killing behaviour: paused, script, no task on worker, ...

**Comment by loicmathieu** [comment] 2023-06-27 10:45
Thinking about it what we can do is:
- When killing an execution from the UI/API: set the execution state to KILLING and send it to the execution queue, stop sending ExecutionKilled in the killQueue
- Inside the executor, when receiving an execution with the state KILLING send an ExecutionKilled to the killQueue

Like this, the responsibility to kill the execution is for the executor not the worker, so it will avoid not being able to kill an execution that has no task running in any worker.

**Comment by anna-geller** [comment] 2023-09-19 08:58
When you try to kill an Execution, the Executor sends a message to the worker to kill the execution (state Killing). If no Worker is working on this execution, it cannot be killed.

Reproducer: once JDBC heartbeats are merged, we can create a shell task with sleep for 10 minutes. We kill the Kestra server, restart it (Worker is now no longer working on that execution and hence cannot kill it), and kill the Execution - it will never be killed in the end.

**Closed** 2023-12-15 20:51 UTC
Labels: bug, backend, large-project
